// 获取字段配置

export const TYPE = 'FINANCE_INVOICE';

export const FETCH_INVOICE_CONFIG_SUCCESS = "FETCH_INVOICE_CONFIG_SUCCESS";

// 获取列表
export const INVOICE_LIST = 'INVOICE_LIST';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const INVOICE_LIST_FAILURE = 'INVOICE_LIST_FAILURE';

export const INVOICE_CONFIRM_FETCHING_TRUE = 'INVOICE_CONFIRM_FETCHING_TRUE';
export const INVOICE_CONFIRM_FETCHING_FALSE = 'INVOICE_CONFIRM_FETCHING_FALSE';

export const FETCH_INVOICE_RECORD_REQUEST = 'FETCH_INVOICE_RECORD_REQUEST';
export const FETCH_INVOICE_RECORD_SUCCESS = 'FETCH_INVOICE_RECORD_SUCCESS';
export const FETCH_INVOICE_RECORD_FAILURE = 'FETCH_INVOICE_RECORD_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/FINANCE/INVOICE/INDEX/FILTER_CONFIG_LIST';
