export const TYPE = 'REPORT_SI';
// 获取销售发票列表
export const FETCH_REPORT_SI_DETAIL = 'REPORT_SI_DETAIL';
export const FETCH_REPORT_SI_DETAIL_SUCCESS = 'REPORT_SI_DETAIL_SUCCESS';
export const FETCH_REPORT_SI_DETAIL_FAILURE = 'REPORT_SI_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_SI_DETAIL_UPDATE_CONFIG = 'REPORT_SI_DETAIL_UPDATE_CONFIG';

