//根据输入值联想物品
export const FETCH_SUGGESTS_BY_KEY_REQUEST = 'COMPONENTS/BUSINESS/LIST_OPE_BAR/FETCH_SUGGESTS_BY_KEY_REQUEST';
export const FETCH_SUGGESTS_BY_KEY_SUCCESS = 'COMPONENTS/BUSINESS/LIST_OPE_BAR/FETCH_SUGGESTS_BY_KEY_SUCCESS';
export const FETCH_SUGGESTS_BY_KEY_FAILURE = 'COMPONENTS/BUSINESS/LIST_OPE_BAR/FETCH_SUGGESTS_BY_KEY_FAILURE';

