//获取项目列表
export const FETCH_PROJECT_LIST_REQUEST = 'FETCH_PROJECT_LIST_REQUEST';
export const FETCH_PROJECT_LIST_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS';
export const FETCH_PROJECT_LIST_FAILURE = 'FETCH_PROJECT_LIST_FAILURE';

//新增/修改/删除部门提交
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE';

export const VISIBLE_PROJECT_REQUEST = 'VISIBLE_PROJECT_REQUEST';
export const VISIBLE_PROJECT_SUCCESS = 'VISIBLE_PROJECT_SUCCESS';
export const VISIBLE_PROJECT_FAILURE = 'VISIBLE_PROJECT_FAILURE';



