export const TYPE = 'PROCESS_LIST';

// 获取字段配置
export const FETCH_PROCESS_LIST_CONFIG_SUCCESS = "PAGES/PRODUCT_CONTROL/PROCESS_LIST/FETCH_PROCESS_LIST_CONFIG_SUCCESS";

export const FETCH_PROCESS_LIST_REQUEST = 'PAGES/PRODUCT_CONTROL/PROCESS_LIST/FETCH_PROCESS_LIST_REQUEST';
export const FETCH_PROCESS_LIST_SUCCESS = 'PAGES/PRODUCT_CONTROL/PROCESS_LIST/FETCH_PROCESS_LIST_SUCCESS';
export const FETCH_PROCESS_LIST_FAILURE = 'PAGES/PRODUCT_CONTROL/PROCESS_LIST/FETCH_PROCESS_LIST_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/PRODUCT_CONTROL/PROCESS_LIST/FILTER_CONFIG_LIST';
