export const TYPE = 'REPORT_INVENTORY_PURCHASE';
// 获取物品列表
export const FETCH_REPORT_PURCHASE_DETAIL = 'REPORT_PURCHASE_DETAIL';
export const FETCH_REPORT_PURCHASE_DETAIL_SUCCESS = 'REPORT_PURCHASE_DETAIL_SUCCESS';
export const FETCH_REPORT_PURCHASE_DETAIL_FAILURE = 'REPORT_PURCHASE_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_PURCHASE_DETAIL_UPDATE_CONFIG = 'REPORT_PURCHASE_DETAIL_UPDATE_CONFIG';

