//获取内贸站物品分类
export const FETCH_CN_GOODS_CATE_LIST_REQUEST = 'FETCH_CN_GOODS_CATE_LIST_REQUEST';
export const FETCH_CN_GOODS_CATE_LIST_SUCCESS = 'FETCH_CN_GOODS_CATE_LIST_SUCCESS';
export const FETCH_CN_GOODS_CATE_LIST_FAILURE = 'FETCH_CN_GOODS_CATE_LIST_FAILURE';

