
//初始化列表数据
export const FETCH_NEW_ONLINE_ORDER_CART_LIST_GET_LIST_DATA_SUCCESS = 'FETCH_NEW_ONLINE_ORDER_CART_LIST_GET_LIST_DATA_SUCCESS';
//获取数据失败
export const FETCH_NEW_ONLINE_ORDER_CART_LIST_DATA_FAILURE = 'FETCH_NEW_ONLINE_ORDER_CART_LIST_DATA_FAILURE';
//获取购物车数量
export const FETCH_MOBILE_CART_NUM = 'FETCH_MOBILE_CART_NUM';

