//获取收支列表
export const FETCH_GROUP_LIST_REQUEST = 'FETCH_GROUP_LIST_REQUEST';
export const FETCH_GROUP_LIST_SUCCESS = 'FETCH_GROUP_LIST_SUCCESS';
export const FETCH_GROUP_LIST_FAILURE = 'FETCH_GROUP_LIST_FAILURE';

//新增/修改/删除收支提交
export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';
