//获取短信通知设置列表
export const FETCH_SMS_NOTIFY_REQUEST = 'FETCH_SMS_NOTIFY_REQUEST';
export const FETCH_SMS_NOTIFY_LIST_SUCCESS = 'FETCH_SMS_NOTIFY_LIST_SUCCESS';
export const FETCH_SMS_NOTIFY_LIST_FAILURE = 'FETCH_SMS_NOTIFY_LIST_FAILURE';


export const ADD_SMS_NOTIFY_REQUEST = 'ADD_SMS_NOTIFY_REQUEST';
export const ADD_SMS_NOTIFY_SUCCESS = 'ADD_SMS_NOTIFY_SUCCESS';
export const ADD_SMS_NOTIFY_FAILURE = 'ADD_SMS_NOTIFY_FAILURE';
