//发送给供应商
export const SEND_TO_SUPPLIER_REQUEST = 'PAGES/PURCHASE/SHOW/SEND_TO_SUPPLIER_REQUEST';
export const SEND_TO_SUPPLIER_SUCCESS = 'PAGES/PURCHASE/SHOW/SEND_TO_SUPPLIER_SUCCESS';
export const SEND_TO_SUPPLIER_FAILURE = 'PAGES/PURCHASE/SHOW/SEND_TO_SUPPLIER_FAILURE';

//发送邮件给供应商
export const SEND_EMAIL_REQUEST = 'PAGES/PURCHASE/SHOW/SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'PAGES/PURCHASE/SHOW/SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'PAGES/PURCHASE/SHOW/SEND_EMAIL_FAILURE';

//获取物流信息
export const EXPRESS_INFO_REQUEST = 'PAGES/PURCHASE/SHOW/EXPRESS_INFO_REQUEST';
export const EXPRESS_INFO_SUCCESS = 'PAGES/PURCHASE/SHOW/EXPRESS_INFO_SUCCESS';
export const EXPRESS_INFO_FAILURE = 'PAGES/PURCHASE/SHOW/EXPRESS_INFO_FAILURE';