//新增子账号
export const ADD_SUB_ACCOUNT_REQUEST = 'ADD_SUB_ACCOUNT_REQUEST';
export const ADD_SUB_ACCOUNT_SUCCESS = 'ADD_SUB_ACCOUNT_SUCCESS';
export const ADD_SUB_ACCOUNT_FAILURE = 'ADD_SUB_ACCOUNT_FAILURE';

export const CHANGE_SUB_ACCOUNT_USER_NAME = 'CHANGE_SUB_ACCOUNT_USER_NAME';
export const CHANGE_SUB_ACCOUNT_PASSWORD = 'CHANGE_SUB_ACCOUNT_PASSWORD';
export const EMPTY_SUB_ACCOUNT_INPUT = 'EMPTY_SUB_ACCOUNT_INPUT';


//根据id获取子账号数据
export const FETCH_SUB_ACCOUNT_BY_ID_REQUEST = 'FETCH_SUB_ACCOUNT_BY_ID_REQUEST';
export const FETCH_SUB_ACCOUNT_BY_ID_SUCCESS = 'FETCH_SUB_ACCOUNT_BY_ID_SUCCESS';
export const FETCH_SUB_ACCOUNT_BY_ID_FAILURE = 'FETCH_SUB_ACCOUNT_BY_ID_FAILURE';

//重置子账号密码
export const RESET_SUB_ACCOUNT_PWD_REQUEST = 'RESET_SUB_ACCOUNT_PWD_REQUEST';
export const RESET_SUB_ACCOUNT_PWD_SUCCESS = 'RESET_SUB_ACCOUNT_PWD_SUCCESS';
export const RESET_SUB_ACCOUNT_PWD_FAILURE = 'RESET_SUB_ACCOUNT_PWD_FAILURE';
