export const TYPE = 'STOCKTAKING';
// 获取字段配置
export const FETCH_STOCKTAKING_CONFIG_SUCCESS = "FETCH_STOCKTAKING_CONFIG_SUCCESS";

// 获取调拨单列表
export const STOCKTAKING_LIST = 'STOCKTAKING_LIST';
export const STOCKTAKING_LIST_SUCCESS = 'STOCKTAKING_LIST_SUCCESS';
export const STOCKTAKING_LIST_FAILURE = 'STOCKTAKING_LIST_FAILURE';

export const GET_LOCAL_STOCKTAKING_INFO = 'GET_LOCAL_STOCKTAKING_INFO';

export const STOCKTAKING_CONFIRM_FETCHING_TRUE = 'STOCKTAKING_CONFIRM_FETCHING_TRUE';
export const STOCKTAKING_CONFIRM_FETCHING_FALSE = 'STOCKTAKING_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const STOCKTAKING_UPDATE_CONFIG = 'STOCKTAKING_UPDATE_CONFIG';

//根据输入值联想客户
export const FETCH_STOCKTAKING_BY_VAL_REQUEST = 'STOCKTAKING/INDEX/FETCH_STOCKTAKING_BY_VAL_REQUEST';
export const FETCH_STOCKTAKING_BY_VAL_SUCCESS = 'STOCKTAKING/INDEX/FETCH_STOCKTAKING_BY_VAL_SUCCESS';
export const FETCH_STOCKTAKING_BY_VAL_FAILURE = 'STOCKTAKING/INDEX/FETCH_STOCKTAKING_BY_VAL_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'STOCKTAKING/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'STOCKTAKING/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'STOCKTAKING/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/STOCKTAKING/INDEX/FILTER_CONFIG_LIST';