//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/MALL/HOME/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/MALL/HOME/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/MALL/HOME/FETCH_PRE_DATA_FAILURE';

//获取商城设定
export const FETCH_SETTING_INFO_REQUEST = 'PAGES/MALL/HOME/FETCH_SETTING_INFO_REQUEST';
export const FETCH_SETTING_INFO_SUCCESS = 'PAGES/MALL/HOME/FETCH_SETTING_INFO_SUCCESS';
export const FETCH_SETTING_INFO_FAILURE = 'PAGES/MALL/HOME/FETCH_SETTING_INFO_FAILURE';

//设置商城提交
export const FETCH_EDIT_MALL_REQUEST = 'PAGES/MALL/HOME/FETCH_EDIT_MALL_REQUEST';
export const FETCH_EDIT_MALL_SUCCESS = 'PAGES/MALL/HOME/FETCH_EDIT_MALL_SUCCESS';
export const FETCH_EDIT_MALL_FAILURE = 'PAGES/MALL/HOME/FETCH_EDIT_MALL_FAILURE';

//开通小程序商城
export const FETCH_OPEN_APPLETS_MALL_REQUEST = 'PAGES/MALL/HOME/FETCH_OPEN_APPLETS_MALL_REQUEST';
export const FETCH_OPEN_APPLETS_MALL_SUCCESS = 'PAGES/MALL/HOME/FETCH_OPEN_APPLETS_MALL_SUCCESS';
export const FETCH_OPEN_APPLETS_MALL_FAILURE = 'PAGES/MALL/HOME/FETCH_OPEN_APPLETS_MALL_FAILURE';

//记录引导出现
export const RECORD_GUIDE_SHOW_REQUEST = 'PAGES/MALL/HOME/RECORD_GUIDE_SHOW_REQUEST';
export const RECORD_GUIDE_SHOW_SUCCESS = 'PAGES/MALL/HOME/RECORD_GUIDE_SHOW_SUCCESS';
export const RECORD_GUIDE_SHOW_FAILURE = 'PAGES/MALL/HOME/RECORD_GUIDE_SHOW_FAILURE';