//新增删除物品条目
export const ADD_GOODS_ITEM = 'COMPONENTS/BUSINESS/FINANCE/ADD_GOODS_ITEM';
export const REMOVE_GOODS_ITEM = 'COMPONENTS/BUSINESS/FINANCE/REMOVE_GOODS_ITEM';
export const INIT_GOODS_ITEM = 'COMPONENTS/BUSINESS/FINANCE/INIT_GOODS_ITEM';

//清空
export const EMPTY_DETAIL_DATA = 'COMPONENTS/BUSINESS/FINANCE/EMPTY_DETAIL_DATA';

