export const TYPE = 'REPORT_INVENTORY_PRICE_UN_TAX';
// 获取物品列表
export const FETCH_REPORT_INVENTORY_PRICE_DETAIL_UN_TAX = 'FETCH_REPORT_INVENTORY_PRICE_DETAIL_UN_TAX';
export const FETCH_REPORT_INVENTORY_PRICE_DETAIL_UN_TAX_SUCCESS = 'FETCH_REPORT_INVENTORY_PRICE_DETAIL_UN_TAX_SUCCESS';
export const FETCH_REPORT_INVENTORY_PRICE_DETAIL_UN_TAX_FAILURE = 'FETCH_REPORT_INVENTORY_PRICE_DETAIL_UN_TAX_FAILURE';



