
//新增MRP运算
export const ADD_MRP_COUNT_REQUEST = 'ADD_MRP_COUNT_REQUEST';
export const ADD_MRP_COUNT_SUCCESS = 'ADD_MRP_COUNT_SUCCESS';
export const ADD_MRP_COUNT_FAILURE = 'ADD_MRP_COUNT_FAILURE';

//获取子级BOM数据
export const GET_NEXT_BOM_DATA_REQUEST = 'GET_NEXT_BOM_DATA_REQUEST';
export const GET_NEXT_BOM_DATA_SUCCESS = 'GET_NEXT_BOM_DATA_SUCCESS';
export const GET_NEXT_BOM_DATA_UPDATE = 'GET_NEXT_BOM_DATA_UPDATE';
export const GET_NEXT_BOM_DATA_FAILURE = 'GET_NEXT_BOM_DATA_FAILURE';
export const GET_NEXT_BOM_UPDATE_TIME = 'GET_NEXT_BOM_UPDATE_TIME';
export const EMPTY_NEXT_BOM_DATA = 'EMPTY_NEXT_BOM_DATA';



//获取页面初始数据
export const FETCH_MRP_COUNT_PRE_DATA_REQUEST = 'FETCH_MRP_COUNT_PRE_DATA_REQUEST';
export const FETCH_MRP_COUNT_PRE_DATA_SUCCESS = 'FETCH_MRP_COUNT_PRE_DATA_SUCCESS';
export const FETCH_MRP_COUNT_PRE_DATA_FAILURE = 'FETCH_MRP_COUNT_PRE_DATA_FAILURE';
