//获取物品单位列表
export const FETCH_GOODS_UNIT_LIST_REQUEST = 'FETCH_GOODS_UNIT_LIST_REQUEST';
export const FETCH_GOODS_UNIT_LIST_SUCCESS = 'FETCH_GOODS_UNIT_LIST_SUCCESS';
export const FETCH_GOODS_UNIT_LIST_FAILURE = 'FETCH_GOODS_UNIT_LIST_FAILURE';

//新增/修改/删除物品单位提交
export const ADD_GOODS_UNIT_REQUEST = 'ADD_GOODS_UNIT_REQUEST';
export const ADD_GOODS_UNIT_SUCCESS = 'ADD_GOODS_UNIT_SUCCESS';
export const ADD_GOODS_UNIT_FAILURE = 'ADD_GOODS_UNIT_FAILURE';
