//更新配置
export const ADD_FIELD_CONFIG = 'COMPONENTS/BUSINESS/GOODS/ADD_FIELD_CONFIG';
export const UPDATE_FIELD_CONFIG = 'COMPONENTS/BUSINESS/GOODS/UPDATE_FIELD_CONFIG';
export const EMPTY_FIELD_CONFIG = 'COMPONENTS/BUSINESS/GOODS/EMPTY_FIELD_CONFIG';

