export const FETCH_ONLINE_ORDER_CART_DETAIL_INIT_CART_DATA = 'FETCH_ONLINE_ORDER_CART_DETAIL_INIT_CART_DATA';

//获取初始化数据
export const FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_SUCCESS = 'FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_SUCCESS';

//错误处理
export const FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_FAILURE = 'FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_FAILURE';


