// 获取字段配置

export const TYPE = 'FINANCE_SALE_INVOICE';

export const FETCH_SALEINVOICE_CONFIG_SUCCESS = "FETCH_SALEINVOICE_CONFIG_SUCCESS";

// 获取列表
export const SALEINVOICE_LIST = 'SALEINVOICE_LIST';
export const SALEINVOICE_LIST_SUCCESS = 'SALEINVOICE_LIST_SUCCESS';
export const SALEINVOICE_LIST_FAILURE = 'SALEINVOICE_LIST_FAILURE';

export const SALEINVOICE_CONFIRM_FETCHING_TRUE = 'SALEINVOICE_CONFIRM_FETCHING_TRUE';
export const SALEINVOICE_CONFIRM_FETCHING_FALSE = 'SALEINVOICE_CONFIRM_FETCHING_FALSE';

export const FETCH_SALEINVOICE_RECORD_REQUEST = 'FETCH_SALEINVOICE_RECORD_REQUEST';
export const FETCH_SALEINVOICE_RECORD_SUCCESS = 'FETCH_SALEINVOICE_RECORD_SUCCESS';
export const FETCH_SALEINVOICE_RECORD_FAILURE = 'FETCH_SALEINVOICE_RECORD_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/FINANCE/SALE_INVOICE/INDEX/FILTER_CONFIG_LIST';