// 获取菜单列表
export const FETCH_MENU_LIST_REQUEST = 'PAGES/AUXILIARY/MENU/FETCH_MENU_LIST_REQUEST';
export const FETCH_MENU_LIST_SUCCESS = 'PAGES/AUXILIARY/MENU/FETCH_MENU_LIST_SUCCESS';
export const FETCH_MENU_LIST_FAILURE = 'PAGES/AUXILIARY/MENU/FETCH_MENU_LIST_FAILURE';
//
// // 更新菜单配置
// export const UPDATE_MENU_REQUEST = 'PAGES/AUXILIARY/MENU/UPDATE_MENU_REQUEST';
// export const UPDATE_MENU_SUCCESS = 'PAGES/AUXILIARY/MENU/UPDATE_MENU_SUCCESS';
// export const UPDATE_MENU_FAILURE = 'PAGES/AUXILIARY/MENU/UPDATE_MENU_FAILURE';
//
