export const TYPE = 'SALE';
// 获取字段配置
export const FETCH_SALE_CONFIG_SUCCESS = "PAGES/SALE/INDEX/FETCH_SALE_CONFIG_SUCCESS";

// 获取物品列表
export const SALE_LIST = 'PAGES/SALE/INDEX/SALE_LIST';
export const SALE_LIST_SUCCESS = 'PAGES/SALE/INDEX/SALE_LIST_SUCCESS';
export const SALE_LIST_FAILURE = 'PAGES/SALE/INDEX/SALE_LIST_FAILURE';

export const GET_LOCAL_SALE_INFO = 'PAGES/SALE/INDEX/GET_LOCAL_SALE_INFO';

export const SALE_CONFIRM_FETCHING_TRUE = 'PAGES/SALE/INDEX/SALE_CONFIRM_FETCHING_TRUE';
export const SALE_CONFIRM_FETCHING_FALSE = 'PAGES/SALE/INDEX/SALE_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const SALE_UPDATE_CONFIG = 'PAGES/SALE/INDEX/SALE_UPDATE_CONFIG';
export const SALE_UPDATE_CONFIG_FIELD_NAME = 'PAGES/SALE/INDEX/SALE_UPDATE_CONFIG_FIELD_NAME';

// 根据物品code获取物品仓库数量
export const FETCH_WARE_BY_CODE_REQUEST = 'PAGES/SALE/INDEX/FETCH_WARE_BY_CODE_REQUEST';
export const FETCH_WARE_BY_CODE_SUCCESS = 'PAGES/SALE/INDEX/FETCH_WARE_BY_CODE_SUCCESS';
export const FETCH_WARE_BY_CODE_FAILURE = 'PAGES/SALE/INDEX/FETCH_WARE_BY_CODE_FAILURE';

// 获取销售记录
export const FETCH_SALE_RECORD_REQUEST = 'PAGES/SALE/INDEX/FETCH_SALE_RECORD_REQUEST';
export const FETCH_SALE_RECORD_SUCCESS = 'PAGES/SALE/INDEX/FETCH_SALE_RECORD_SUCCESS';
export const FETCH_SALE_RECORD_FAILURE = 'PAGES/SALE/INDEX/FETCH_SALE_RECORD_FAILURE';

// 获取销售批量出库信息
export const FETCH_SALE_BATCH_OUT_INFO_REQUEST = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_OUT_INFO_REQUEST';
export const FETCH_SALE_BATCH_OUT_INFO_SUCCESS = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_OUT_INFO_SUCCESS';
export const FETCH_SALE_BATCH_OUT_INFO_FAILURE = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_OUT_INFO_FAILURE';

// 获取销售订单批量收款信息，（待收款信息）
export const FETCH_SALE_BATCH_PRE_INCOME_REQUEST = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_PRE_INCOME_REQUEST';
export const FETCH_SALE_BATCH_PRE_INCOME_SUCCESS = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_PRE_INCOME_SUCCESS';
export const FETCH_SALE_BATCH_PRE_INCOME_FAILURE = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_PRE_INCOME_FAILURE';

// 获取销售订单批量开票信息
export const FETCH_SALE_BATCH_PRE_SALEINVOICE_REQUEST = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_PRE_SALEINVOICE_REQUEST';
export const FETCH_SALE_BATCH_PRE_SALEINVOICE_SUCCESS = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_PRE_SALEINVOICE_SUCCESS';
export const FETCH_SALE_BATCH_PRE_SALEINVOICE_FAILURE = 'PAGES/SALE/INDEX/FETCH_SALE_BATCH_PRE_SALEINVOICE_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'PAGES/SALE/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'PAGES/SALE/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'PAGES/SALE/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/SALE/INDEX/FILTER_CONFIG_LIST';