//获取百卓所有类目列表
export const FETCH_ABIZ_ALL_CATE_REQUEST = 'FETCH_ABIZ_ALL_CATE_REQUEST';
export const FETCH_ABIZ_ALL_CATE_SUCCESS = 'FETCH_ABIZ_ALL_CATE_SUCCESS';
export const FETCH_ABIZ_ALL_CATE_FAILURE = 'FETCH_ABIZ_ALL_CATE_FAILURE';

