export const TYPE = 'REQUISITION_ORDER';

// 获取字段配置
export const FETCH_REQUISITION_ORDER_CONFIG_SUCCESS = "FETCH_REQUISITION_ORDER_CONFIG_SUCCESS";

//获取请购单列表数据
export const FETCH_REQUISITION_ORDER_LIST_REQUEST = 'FETCH_REQUISITION_ORDER_LIST_REQUEST';
export const FETCH_REQUISITION_ORDER_LIST_SUCCESS = 'FETCH_REQUISITION_ORDER_LIST_SUCCESS';
export const FETCH_REQUISITION_ORDER_LIST_FAILURE = 'FETCH_REQUISITION_ORDER_LIST_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_REQUEST = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_SUCCESS = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_FAILURE = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/REQUISITION_ORDER/INDEX/FILTER_CONFIG_LIST';



