export const TYPE = 'QUOTATION';
// 获取字段配置
export const FETCH_QUOTATION_CONFIG_SUCCESS = "PAGES/QUOTATION/INDEX/FETCH_SALE_CONFIG_SUCCESS";

// 获取物品列表
export const QUOTATION_LIST = 'PAGES/QUOTATION/INDEX/SALE_LIST';
export const QUOTATION_LIST_SUCCESS = 'PAGES/QUOTATION/INDEX/SALE_LIST_SUCCESS';
export const QUOTATION_LIST_FAILURE = 'PAGES/QUOTATION/INDEX/SALE_LIST_FAILURE';

export const GET_LOCAL_QUOTATION_INFO = 'PAGES/QUOTATION/INDEX/GET_LOCAL_SALE_INFO';

export const QUOTATION_CONFIRM_FETCHING_TRUE = 'PAGES/QUOTATION/INDEX/SALE_CONFIRM_FETCHING_TRUE';
export const QUOTATION_CONFIRM_FETCHING_FALSE = 'PAGES/QUOTATION/INDEX/SALE_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const QUOTATION_UPDATE_CONFIG = 'PAGES/QUOTATION/INDEX/SALE_UPDATE_CONFIG';
export const QUOTATION_UPDATE_CONFIG_FIELD_NAME = 'PAGES/QUOTATION/INDEX/SALE_UPDATE_CONFIG_FIELD_NAME';

// 根据物品code获取物品仓库数量
export const FETCH_WARE_BY_CODE_REQUEST = 'PAGES/QUOTATION/INDEX/FETCH_WARE_BY_CODE_REQUEST';
export const FETCH_WARE_BY_CODE_SUCCESS = 'PAGES/QUOTATION/INDEX/FETCH_WARE_BY_CODE_SUCCESS';
export const FETCH_WARE_BY_CODE_FAILURE = 'PAGES/QUOTATION/INDEX/FETCH_WARE_BY_CODE_FAILURE';

// 获取销售记录
export const FETCH_SALE_RECORD_REQUEST = 'PAGES/SALE/INDEX/FETCH_SALE_RECORD_REQUEST';
export const FETCH_SALE_RECORD_SUCCESS = 'PAGES/SALE/INDEX/FETCH_SALE_RECORD_SUCCESS';
export const FETCH_SALE_RECORD_FAILURE = 'PAGES/SALE/INDEX/FETCH_SALE_RECORD_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'PAGES/QUOTATION/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'PAGES/QUOTATION/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'PAGES/QUOTATION/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/QUOTATION/INDEX/FILTER_CONFIG_LIST';