
//新增收入记录
export const ADD_SALEINVOICE_REQUEST = 'ADD_SALEINVOICE_REQUEST';
export const ADD_SALEINVOICE_SUCCESS = 'ADD_SALEINVOICE_SUCCESS';
export const ADD_SALEINVOICE_FAILURE = 'ADD_SALEINVOICE_FAILURE';

//根据物income id获取收入记录信息
export const FETCH_SALEINVOICE_BY_ID_REQUEST = 'FETCH_SALEINVOICE_BY_ID_REQUEST';
export const FETCH_SALEINVOICE_BY_ID_SUCCESS = 'FETCH_SALEINVOICE_BY_ID_SUCCESS';
export const FETCH_SALEINVOICE_BY_ID_FAILURE = 'FETCH_SALEINVOICE_BY_ID_FAILURE';

//获取收支列表
export const FETCH_SALEINVOICE_LIST_REQUEST = 'FETCH_SALEINVOICE_LIST_REQUEST';
export const FETCH_SALEINVOICE_LIST_SUCCESS = 'FETCH_SALEINVOICE_LIST_SUCCESS';
export const FETCH_SALEINVOICE_LIST_FAILURE = 'FETCH_SALEINVOICE_LIST_FAILURE';