//Mrp详情页信息
export const Mrp_COUNT_DETAIL_REQUEST = 'Mrp_COUNT_DETAIL_REQUEST';
export const Mrp_COUNT_DETAIL_SUCCESS = 'Mrp_COUNT_DETAIL_SUCCESS';
export const Mrp_COUNT_DETAIL_FAILURE = 'Mrp_COUNT_DETAIL_FAILURE';