//订单通知
export const FETCH_ORDER_NOTICE_REQUEST = 'COMPONENTS/LAYOUT/HEADER/FETCH_ORDER_NOTICE_REQUEST';
export const FETCH_ORDER_NOTICE_SUCCESS = 'COMPONENTS/LAYOUT/HEADER/FETCH_ORDER_NOTICE_SUCCESS';
export const FETCH_ORDER_NOTICE_FAILURE = 'COMPONENTS/LAYOUT/HEADER/FETCH_ORDER_NOTICE_FAILURE';

//好友通知
export const FETCH_FRIEND_NOTICE_REQUEST = 'COMPONENTS/LAYOUT/HEADER/FETCH_FRIEND_NOTICE_REQUEST';
export const FETCH_FRIEND_NOTICE_SUCCESS = 'COMPONENTS/LAYOUT/HEADER/FETCH_FRIEND_NOTICE_SUCCESS';
export const FETCH_FRIEND_NOTICE_FAILURE = 'COMPONENTS/LAYOUT/HEADER/FETCH_FRIEND_NOTICE_FAILURE';