//获取当前账号信息
export const FETCH_ACCOUT_INFO = 'FETCH_ACCOUT_INFO';
export const FETCH_ACCOUT_INFO_SUCCESS = 'FETCH_ACCOUT_INFO_SUCCESS';
export const FETCH_ACCOUT_INFO_FAILURE = 'FETCH_ACCOUT_INFO_FAILURE';

export const FETCH_ONLINE_MALL_SUCCESS = '/COMPONENTS/BUSINESS/COMMON/REQUEST/FETCH_ONLINE_MALL_SUCCESS';

export const FETCH_INIT_LIST_CONDITION_SUCCESS = '/COMPONENTS/BUSINESS/COMMON/REQUEST/FETCH_INIT_LIST_CONDITION_SUCCESS';

export const ASYNC_FETCH_MESSAGE_RECOMMEND_LOG = '/COMPONENTS/BUSINESS/COMMON/REQUEST/ASYNC_FETCH_MESSAGE_RECOMMEND_LOG';
export const ASYNC_MESSAGE_RECOMMEND = '/COMPONENTS/BUSINESS/COMMON/REQUEST/ASYNC_MESSAGE_RECOMMEND';
