export const TYPE = 'CUSTOMER';
// 获取字段配置
export const FETCH_CUSTOMER_CONFIG_SUCCESS = "FETCH_CUSTOMER_CONFIG_SUCCESS";

// 获取客户列表
export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_FAILURE = 'CUSTOMER_LIST_FAILURE';

// 获取客户申请列表
export const CUSTOMER_APPLY_LIST = 'CUSTOMER_APPLY_LIST';
export const CUSTOMER_APPLY_LIST_SUCCESS = 'CUSTOMER_APPLY_LIST_SUCCESS';
export const CUSTOMER_APPLY_LIST_FAILURE = 'CUSTOMER_APPLY_LIST_FAILURE';

export const GET_LOCAL_CUSTOMER_INFO = 'GET_LOCAL_CUSTOMER_INFO';

export const CUSTOMER_CONFIRM_FETCHING_TRUE = 'CUSTOMER_CONFIRM_FETCHING_TRUE';
export const CUSTOMER_CONFIRM_FETCHING_FALSE = 'CUSTOMER_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const CUSTOMER_UPDATE_CONFIG = 'CUSTOMER_UPDATE_CONFIG';

//根据输入值联想客户
export const FETCH_CUSTOMER_BY_VAL_REQUEST = 'CUSTOMER/INDEX/FETCH_CUSTOMER_BY_VAL_REQUEST';
export const FETCH_CUSTOMER_BY_VAL_SUCCESS = 'CUSTOMER/INDEX/FETCH_CUSTOMER_BY_VAL_SUCCESS';
export const FETCH_CUSTOMER_BY_VAL_FAILURE = 'CUSTOMER/INDEX/FETCH_CUSTOMER_BY_VAL_FAILURE';

// 获取客户价格表
export const FETCH_CUSTOMER_PRICE_RECORD_REQUEST = 'FETCH_CUSTOMER_PRICE_RECORD_REQUEST';
export const FETCH_CUSTOMER_PRICE_RECORD_SUCCESS = 'FETCH_CUSTOMER_PRICE_RECORD_SUCCESS';
export const FETCH_CUSTOMER_PRICE_RECORD_FAILURE = 'FETCH_CUSTOMER_PRICE_RECORD_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/CUSTOMER/INDEX/FILTER_CONFIG_LIST';