//获取下载中心列表
export const FETCH_DOWNLOAD_CENTER_REQUEST = 'FETCH_DOWNLOAD_CENTER_REQUEST';
export const FETCH_DOWNLOAD_CENTER_SUCCESS = 'FETCH_DOWNLOAD_CENTER_SUCCESS';
export const FETCH_DOWNLOAD_CENTER_FAILURE = 'FETCH_DOWNLOAD_CENTER_FAILURE';
