//根据输入值联想物品
export const FETCH_GOODS_BY_VAL_REQUEST = 'GOODS/SUGGEST/FETCH_GOODS_BY_VAL_REQUEST';
export const FETCH_GOODS_BY_VAL_SUCCESS = 'GOODS/SUGGEST/FETCH_GOODS_BY_VAL_SUCCESS';
export const FETCH_GOODS_BY_VAL_FAILURE = 'GOODS/SUGGEST/FETCH_GOODS_BY_VAL_FAILURE';

