
export const TYPE = 'REPORT_CHECK_CUSTOMER';

// 获取物品列表
export const FETCH_REPORT_SALEOUT_DETAIL = 'REPORT_SALEOUT_DETAIL';
export const FETCH_REPORT_SALEOUT_DETAIL_SUCCESS = 'REPORT_SALEOUT_DETAIL_SUCCESS';
export const FETCH_REPORT_SALEOUT_DETAIL_FAILURE = 'REPORT_SALEOUT_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_SALEOUT_DETAIL_UPDATE_CONFIG = 'REPORT_SALEOUT_DETAIL_UPDATE_CONFIG';

