//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/REQUISITION_ORDER/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/REQUISITION_ORDER/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/REQUISITION_ORDER/ADD/FETCH_PRE_DATA_FAILURE';


//请购单新增
export const ADD_REQUISITION_ORDER_REQUEST = 'ADD_REQUISITION_ORDER_REQUEST';
export const ADD_REQUISITION_ORDER_SUCCESS = 'ADD_REQUISITION_ORDER_SUCCESS';
export const ADD_REQUISITION_ORDER_FAILURE = 'ADD_REQUISITION_ORDER_FAILURE';

//根据id获取请购单信息
export const FETCH_REQUISITION_ORDER_BY_ID_REQUEST = 'FETCH_REQUISITION_ORDER_BY_ID_REQUEST';
export const FETCH_REQUISITION_ORDER_BY_ID_SUCCESS = 'FETCH_REQUISITION_ORDER_BY_ID_SUCCESS';
export const FETCH_REQUISITION_ORDER_BY_ID_FAILURE = 'FETCH_REQUISITION_ORDER_BY_ID_FAILURE';

//清空请购单
export const EMPTY_DETAIL_DATA = 'PAGES/REQUISITION_ORDER/ADD/EMPTY_DETAIL_DATA';








