

//获取部门列表
export const FETCH_CUSTOM_FIELD_LIST_REQUEST = 'FETCH_CUSTOM_FIELD_LIST_REQUEST';
export const FETCH_CUSTOM_FIELD_LIST_SUCCESS = 'FETCH_CUSTOM_FIELD_LIST_SUCCESS';
export const FETCH_CUSTOM_FIELD_LIST_FAILURE = 'FETCH_CUSTOM_FIELD_LIST_FAILURE';

//新增/修改/删除部门提交
export const ADD_CUSTOM_FIELD_REQUEST = 'ADD_CUSTOM_FIELD_REQUEST';
export const ADD_CUSTOM_FIELD_SUCCESS = 'ADD_CUSTOM_FIELD_SUCCESS';
export const ADD_CUSTOM_FIELD_FAILURE = 'ADD_CUSTOM_FIELD_FAILURE';
