export const TYPE = 'REPORT_FIO';
// 获取物品列表
export const FETCH_REPORT_FIO_DETAIL = 'REPORT_FIO_DETAIL';
export const FETCH_REPORT_FIO_DETAIL_SUCCESS = 'REPORT_FIO_DETAIL_SUCCESS';
export const FETCH_REPORT_FIO_DETAIL_FAILURE = 'REPORT_FIO_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_FIO_DETAIL_UPDATE_CONFIG = 'REPORT_FIO_DETAIL_UPDATE_CONFIG';

