//初始化列表数据
export const FETCH_ONLINE_ORDER_CUSTOMER_DATA_SUCCESS = 'FETCH_ONLINE_ORDER_CUSTOMER_DATA_SUCCESS';
//获取数据失败
export const FETCH_ONLINE_ORDER_CUSTOMER_DATA_FAILURE = 'FETCH_ONLINE_ORDER_CUSTOMER_DATA_FAILURE';
