//获取收支列表
export const FETCH_ADDRESS_LIST_REQUEST = 'FETCH_ADDRESS_LIST_REQUEST';
export const FETCH_ADDRESS_LIST_SUCCESS = 'FETCH_ADDRESS_LIST_SUCCESS';
export const FETCH_ADDRESS_LIST_FAILURE = 'FETCH_ADDRESS_LIST_FAILURE';

//新增/修改/删除收支提交
export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';
