//新增删除物品条目
export const ADD_GOODS_ITEM = 'COMPONENTS/BUSINESS/GOODS/ADD_GOODS_ITEM';
export const REMOVE_GOODS_ITEM = 'COMPONENTS/BUSINESS/GOODS/REMOVE_GOODS_ITEM';
export const INIT_GOODS_ITEM = 'COMPONENTS/BUSINESS/GOODS/INIT_GOODS_ITEM';
export const INIT_GOODS_DEFAULT_ITEM = 'COMPONENTS/BUSINESS/GOODS/INIT_GOODS_DEFAULT_ITEM';

//扫码录单（根据物品条码获取物品信息）
export const FETCH_SALE_BY_BARCODE_REQUEST = 'COMPONENTS/BUSINESS/GOODS/FETCH_SALE_BY_BARCODE_REQUEST';
export const FETCH_SALE_BY_BARCODE_SUCCESS = 'COMPONENTS/BUSINESS/GOODS/FETCH_SALE_BY_BARCODE_SUCCESS';
export const FETCH_SALE_BY_BARCODE_FAILURE = 'COMPONENTS/BUSINESS/GOODS/FETCH_SALE_BY_BARCODE_FAILURE';

export const SET_FIELD_READONLY = 'COMPONENTS/BUSINESS/GOODS/SET_FIELD_READONLY';
export const UNSET_FIELD_READONLY = 'COMPONENTS/BUSINESS/GOODS/UNSET_FIELD_READONLY';

// 根据物品code获取物品库存信息
export const FETCH_STOCK_BY_CODE_REQUEST = 'COMPONENTS/BUSINESS/GOODS/FETCH_STOCK_BY_CODE_REQUEST';
export const FETCH_STOCK_BY_CODE_SUCCESS = 'COMPONENTS/BUSINESS/GOODS/FETCH_STOCK_BY_CODE_SUCCESS';
export const FETCH_STOCK_BY_CODE_FAILURE = 'COMPONENTS/BUSINESS/GOODS/FETCH_STOCK_BY_CODE_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'COMPONENTS/BUSINESS/GOODS/EMPTY_DETAIL_DATA';


