
//新增收入记录
export const ADD_EXPEND_REQUEST = 'ADD_EXPEND_REQUEST';
export const ADD_EXPEND_SUCCESS = 'ADD_EXPEND_SUCCESS';
export const ADD_EXPEND_FAILURE = 'ADD_EXPEND_FAILURE';

//根据物income id获取收入记录信息
export const FETCH_EXPEND_BY_ID_REQUEST = 'FETCH_EXPEND_BY_ID_REQUEST';
export const FETCH_EXPEND_BY_ID_SUCCESS = 'FETCH_EXPEND_BY_ID_SUCCESS';
export const FETCH_EXPEND_BY_ID_FAILURE = 'FETCH_EXPEND_BY_ID_FAILURE';

//获取收支列表
export const FETCH_EXPEND_LIST_REQUEST = 'FETCH_EXPEND_LIST_REQUEST';
export const FETCH_EXPEND_LIST_SUCCESS = 'FETCH_EXPENDLIST_SUCCESS';
export const FETCH_EXPEND_LIST_FAILURE = 'FETCH_EXPEND_LIST_FAILURE';