//发送给供应商
export const FETCH_PRODUCT_CONTROL_BY_ID_REQUEST = 'PAGES/PRODUCT_CONTROL/SHOW/FETCH_PRODUCT_CONTROL_BY_ID_REQUEST';
export const FETCH_PRODUCT_CONTROL_BY_ID_SUCCESS = 'PAGES/PRODUCT_CONTROL/SHOW/FETCH_PRODUCT_CONTROL_BY_ID_SUCCESS';
export const FETCH_PRODUCT_CONTROL_BY_ID_FAILURE = 'PAGES/PRODUCT_CONTROL/SHOW/FETCH_PRODUCT_CONTROL_BY_ID_FAILURE';


export const ASYNC_OPERATE_WORKSHEET = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_OPERATE_WORKSHEET';
export const ASYNC_OPERATE_WORKSHEET_PROCESS = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_OPERATE_WORKSHEET_PROCESS';

export const ASYNC_FETCH_WORK_SHEET_REPORT = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_FETCH_WORK_SHEET_REPORT';
export const ASYNC_ADD_WORK_SHEET_REPORT = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_ADD_WORK_SHEET_REPORT';
export const ASYNC_DELETE_WORK_SHEET_REPORT = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_DELETE_WORK_SHEET_REPORT';

// 获取操作日志
export const ASYNC_FETCH_OPERATION_LOG_REQUEST = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_FETCH_OPERATION_LOG_REQUEST';

// 发送短信提醒
export const ASYNC_MESSAGE_RECOMMEND = 'PAGES/PRODUCT_CONTROL/SHOW/ASYNC_MESSAGE_RECOMMEND';





