//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/QUOTATION/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/QUOTATION/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/QUOTATION/ADD/FETCH_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_QUOTATION_REQUEST = 'PAGES/QUOTATION/ADD/ADD_SALE_REQUEST';
export const ADD_QUOTATION_SUCCESS = 'PAGES/QUOTATION/ADD/ADD_SALE_SUCCESS';
export const ADD_QUOTATION_FAILURE = 'PAGES/QUOTATION/ADD/ADD_SALE_FAILURE';

//根据物品id获取物品信息
export const FETCH_QUOTATION_BY_ID_REQUEST = 'PAGES/QUOTATION/ADD/FETCH_SALE_BY_ID_REQUEST';
export const FETCH_QUOTATION_BY_ID_SUCCESS = 'PAGES/QUOTATION/ADD/FETCH_SALE_BY_ID_SUCCESS';
export const FETCH_QUOTATION_BY_ID_FAILURE = 'PAGES/QUOTATION/ADD/FETCH_SALE_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/QUOTATION/ADD/EMPTY_DETAIL_DATA';

export const UPDATE_BIND_PRODUCT_INFO = 'PAGES/QUOTATION/DETAIL/UPDATE_BIND_PRODUCT_INFO';
export const REQUEST_BIND_PRODUCT = 'PAGES/QUOTATION/DETAIL/REQUEST_BIND_PRODUCT_INFO';
export const REQUEST_BIND_PRODUCT_SUCCESS = 'PAGES/QUOTATION/DETAIL/REQUEST_BIND_PRODUCT_SUCCESS';
export const REQUEST_BIND_PRODUCT_FAILED = 'PAGES/QUOTATION/DETAIL/REQUEST_BIND_PRODUCT_FAILED';

//获取操作日志
export const ASYNC_FETCH_OPERATION_LOG_REQUEST = 'PAGES/QUOTATION/ADD/ASYNC_FETCH_OPERATION_LOG_REQUEST';
export const ASYNC_FETCH_OPERATION_LOG_SUCCESS = 'PAGES/QUOTATION/ADD/ASYNC_FETCH_OPERATION_LOG_SUCCESS';
export const ASYNC_FETCH_OPERATION_LOG_FAILURE = 'PAGES/QUOTATION/ADD/ASYNC_FETCH_OPERATION_LOG_FAILURE';
