export const TYPE = 'REPORT_BATCH_QUERY';
// 获取物品列表
export const FETCH_REPORT_BATCH_QUERY = 'FETCH_REPORT_BATCH_QUERY';
export const FETCH_REPORT_BATCH_QUERY_SUCCESS = 'FETCH_REPORT_BATCH_QUERY_SUCCESS';
export const FETCH_REPORT_BATCH_QUERY_FAILURE = 'FETCH_REPORT_BATCH_QUERY_FAILURE';

export const MODIFY_BATCH_QUERY_REQUEST = 'MODIFY_BATCH_QUERY_REQUEST';
export const MODIFY_BATCH_QUERY_SUCCESS = 'MODIFY_BATCH_QUERY_SUCCESS';
export const MODIFY_BATCH_QUERY_FAILURE = 'MODIFY_BATCH_QUERY_FAILURE';

export const FETCH_BATCH_MODIFY_LIST_REQUEST = 'FETCH_BATCH_MODIFY_LIST_REQUEST';
export const FETCH_BATCH_MODIFY_LIST_SUCCESS = 'FETCH_BATCH_MODIFY_LIST_SUCCESS';
export const FETCH_BATCH_MODIFY_LIST_FAILURE = 'FETCH_BATCH_MODIFY_LIST_FAILURE';
