//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/PRODUCE_ORDER/ADD_RECORD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/PRODUCE_ORDER/ADD_RECORD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/PRODUCE_ORDER/ADD_RECORD/FETCH_PRE_DATA_FAILURE';

//新增生产单提交
export const ADD_PRODUCE_ORDER_RECORD_REQUEST = 'PAGES/PRODUCE_ORDER/ADD_RECORD/ADD_PRODUCE_ORDER_RECORD_REQUEST';
export const ADD_PRODUCE_ORDER_RECORD_SUCCESS = 'PAGES/PRODUCE_ORDER/ADD_RECORD/ADD_PRODUCE_ORDER_RECORD_SUCCESS';
export const ADD_PRODUCE_ORDER_RECORD_FAILURE = 'PAGES/PRODUCE_ORDER/ADD_RECORD/ADD_PRODUCE_ORDER_RECORD_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/PRODUCE_ORDER/ADD_RECORD/EMPTY_DETAIL_DATA';







