export const TYPE = 'REPORT_INVENTORY_INQUIRY';
// 获取物品列表
export const FETCH_REPORT_INVENTORY_INQUIRY = 'FETCH_REPORT_INVENTORY_INQUIRY';
export const FETCH_REPORT_INVENTORY_INQUIRY_SUCCESS = 'FETCH_REPORT_INVENTORY_INQUIRY_SUCCESS';
export const FETCH_REPORT_INVENTORY_INQUIRY_FAILURE = 'FETCH_REPORT_INVENTORY_INQUIRY_FAILURE';

// 更新配置字段
export const REPORT_INVENTORY_INQUIRY_UPDATE_CONFIG = 'REPORT_INVENTORY_INQUIRY_UPDATE_CONFIG';

