export const TYPE = 'REPORT_SALE';
// 获取物品列表
export const FETCH_REPORT_SALE_DETAIL = 'REPORT_SALE_DETAIL';
export const FETCH_REPORT_SALE_DETAIL_SUCCESS = 'REPORT_SALE_DETAIL_SUCCESS';
export const FETCH_REPORT_SALE_DETAIL_FAILURE = 'REPORT_SALE_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_SALE_DETAIL_UPDATE_CONFIG = 'REPORT_SALE_DETAIL_UPDATE_CONFIG';

