//设备管理列表
export const FETCH_DEVICE_MANAGE_LIST_REQUEST = 'FETCH_DEVICE_MANAGE_LIST_REQUEST';
export const FETCH_DEVICE_MANAGE_LIST_SUCCESS = 'FETCH_DEVICE_MANAGE_LIST_SUCCESS';
export const FETCH_DEVICE_MANAGE_LIST_FAILURE = 'FETCH_DEVICE_MANAGE_LIST_FAILURE';

//新增/修改/删除设备
export const ADD_DEVICE_MANAGE_REQUEST = 'ADD_DEVICE_MANAGE_REQUEST';
export const ADD_DEVICE_MANAGE_SUCCESS = 'ADD_DEVICE_MANAGE_SUCCESS';
export const ADD_DEVICE_MANAGE_FAILURE = 'ADD_DEVICE_MANAGE_FAILURE';
