//获取项目列表
export const FETCH_CUSTOMER_LV_LIST_REQUEST = 'FETCH_CUSTOMER_LV_LIST_REQUEST';
export const FETCH_CUSTOMER_LV_LIST_SUCCESS = 'FETCH_CUSTOMER_LV_LIST_SUCCESS';
export const FETCH_CUSTOMER_LV_LIST_FAILURE = 'FETCH_CUSTOMER_LV_LIST_FAILURE';

//新增/修改/删除部门提交
export const ADD_CUSTOMER_LV_REQUEST = 'ADD_CUSTOMER_LV_REQUEST';
export const ADD_CUSTOMER_LV_SUCCESS = 'ADD_CUSTOMER_LV_SUCCESS';
export const ADD_CUSTOMER_LV_FAILURE = 'ADD_CUSTOMER_LV_FAILURE';
