export const TYPE = 'REPORT_FETCH_INACTIVE_STOCK';
// 获取呆滞料报表列表
export const FETCH_INACTIVE_STOCK = 'PAGES/REPORT/FETCH_INACTIVE_STOCK';

// 更新配置字段
// export const FETCH_SALE_REFUND_SUMMARY_BY_PROD = 'REPORT_SALE_REFUND_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG';

