//子账号列表
export const FETCH_SUB_ACCOUNT_LIST_REQUEST = 'FETCH_SUB_ACCOUNT_LIST_REQUEST';
export const FETCH_SUB_ACCOUNT_LIST_SUCCESS = 'FETCH_SUB_ACCOUNT_LIST_SUCCESS';
export const FETCH_SUB_ACCOUNT_LIST_FAILURE = 'FETCH_SUB_ACCOUNT_LIST_FAILURE';

//切换账号列表
export const FETCH_SWITCH_ACCOUNT_LIST_REQUEST = 'FETCH_SWITCH_ACCOUNT_LIST_REQUEST';
export const FETCH_SWITCH_ACCOUNT_LIST_SUCCESS = 'FETCH_SWITCH_ACCOUNT_LIST_SUCCESS';
export const FETCH_SWITCH_ACCOUNT_LIST_FAILURE = 'FETCH_SWITCH_ACCOUNT_LIST_FAILURE';

//停用/启用
export const FETCH_USER_STATUS_REQUEST = 'FETCH_USER_STATUS_REQUEST';
export const FETCH_USER_STATUS_SUCCESS = 'FETCH_USER_STATUS_SUCCESS';
export const FETCH_USER_STATUS_FAILURE = 'FETCH_USER_STATUS_FAILURE';

export const ASSIGN_TO_SUB_ACCOUNT_REQUEST = 'ASSIGN_TO_SUB_ACCOUNT_REQUEST';
export const ASSIGN_TO_SUB_ACCOUNT_SUCCESS = 'ASSIGN_TO_SUB_ACCOUNT_SUCCESS';
export const ASSIGN_TO_SUB_ACCOUNT_FAILURE = 'ASSIGN_TO_SUB_ACCOUNT_FAILURE';

export const EMPTY_SUB_ACCOUNT_LIST = 'EMPTY_SUB_ACCOUNT_LIST';
export const SUB_ACCOUNT_CHECK= 'ACCOUNT/INDEX/SUB_ACCOUNT_CHECK';