//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'GOODS/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'GOODS/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'GOODS/ADD/FETCH_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_GOODS_REQUEST = 'GOODS/ADD/ADD_GOODS_REQUEST';
export const ADD_GOODS_SUCCESS = 'GOODS/ADD/ADD_GOODS_SUCCESS';
export const ADD_GOODS_FAILURE = 'GOODS/ADD/ADD_GOODS_FAILURE';

//根据物品id获取物品信息
export const FETCH_GOODS_BY_ID_REQUEST = 'GOODS/ADD/FETCH_GOODS_BY_ID_REQUEST';
export const FETCH_GOODS_BY_ID_SUCCESS = 'GOODS/ADD/FETCH_GOODS_BY_ID_SUCCESS';
export const FETCH_GOODS_BY_ID_FAILURE = 'GOODS/ADD/FETCH_GOODS_BY_ID_FAILURE';

//上传图片
export const UPLOAD_PIC_CHANGE = 'GOODS/ADD/UPLOAD_PIC_CHANGE';
export const DELETE_PIC_CHANGE = 'GOODS/ADD/DELETE_PIC_CHANGE';
export const EMPTY_UPLOAD_PIC_DATA = 'GOODS/ADD/EMPTY_UPLOAD_PIC_DATA';


// 根据物品code获取物品库存信息
export const FETCH_STOCK_BY_CODE_REQUEST = 'GOODS/ADD/FETCH_STOCK_BY_CODE_REQUEST';
export const FETCH_STOCK_BY_CODE_SUCCESS = 'GOODS/ADD/FETCH_STOCK_BY_CODE_SUCCESS';
export const FETCH_STOCK_BY_CODE_FAILURE = 'GOODS/ADD/FETCH_STOCK_BY_CODE_FAILURE';