export const FETCH_ONLINE_ORDER_CART_GET_DETAIL_DATA = 'FETCH_ONLINE_ORDER_CART_GET_DETAIL_DATA';

export const FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_FAILURE = 'FETCH_ONLINE_ORDER_CART_GET_DETAIL_DATA';

//获取table数据
export const FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_SUCCESS = 'FETCH_ONLINE_ORDER_CART_DETAIL_GET_DATA_SUCCESS';


