// 取消在线销售订单请求
export const CANCEL_SCHEDULING_REQUEST = 'CANCEL_SCHEDULING_REQUEST';
export const CANCEL_SCHEDULING_SUCCESS = 'CANCEL_SCHEDULING_SUCCESS';
export const CANCEL_SCHEDULING_FAILURE = 'CANCEL_SCHEDULING_FAILURE';

// 接收在线销售订单请求
export const ACCEPT_SCHEDULING_REQUEST = 'ACCEPT_SCHEDULING_REQUEST';
export const ACCEPT_SCHEDULING_SUCCESS = 'ACCEPT_SCHEDULING_SUCCESS';
export const ACCEPT_SCHEDULING_FAILURE = 'ACCEPT_SCHEDULING_FAILURE';
