// 获取销售列表
export const TRACE_SALE_LIST = 'PAGES/TRACE/SALE/INDEX/SALE_LIST';
export const TRACE_SALE_LIST_SUCCESS = 'PAGES/TRACE/SALE/INDEX/SALE_LIST_SUCCESS';
export const TRACE_SALE_LIST_FAILURE = 'PAGES/TRACE/SALE/INDEX/SALE_LIST_FAILURE';

export const TRACE_SALE_UPDATE_CONFIG_FIELD_NAME = 'PAGES/TRACE/SALE/INDEX/SALE_UPDATE_CONFIG_FIELD_NAME';

export const TYPE = 'TRACE_SALE';

