export const FETCH_ONLINE_ORDER_CART_INIT_CART_LIST = 'FETCH_ONLINE_ORDER_CART_INIT_CART_LIST';
export const FETCH_ONLINE_ORDER_CART_GET_INVALID_DATA_SUCCESS = 'FETCH_ONLINE_ORDER_CART_GET_INVALID_DATA_SUCCESS';
export const FETCH_ONLINE_ORDER_CART_GET_INVALID_DATA_FAILURE = 'FETCH_ONLINE_ORDER_CART_GET_INVALID_DATA_FAILURE';


//选择单挑产品
export const FETCH_ONLINE_ORDER_CART_CLICK_ONE_LIST = 'FETCH_ONLINE_ORDER_CART_CLICK_ONE_LIST';
//选择一个公司对应的所有产品
export const FETCH_ONLINE_ORDER_CART_CLICK_All_LIST = 'FETCH_ONLINE_ORDER_CART_CLICK_All_LIST';
//选择全部的产品
export const FETCH_ONLINE_ORDER_CART_CLICK_TOTAL_LIST = 'FETCH_ONLINE_ORDER_CART_CLICK_TOTAL_LIST';
//改变数量
export const FETCH_ONLINE_ORDER_CART_CHANGE_AMOUNT = 'FETCH_ONLINE_ORDER_CART_CHANGE_AMOUNT';