//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/STOCKTAKING/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/STOCKTAKING/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/STOCKTAKING/ADD/FETCH_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_STOCKTAKING_REQUEST = 'PAGES/STOCKTAKING/ADD/ADD_STOCKTAKING_REQUEST';
export const ADD_STOCKTAKING_SUCCESS = 'PAGES/STOCKTAKING/ADD/ADD_STOCKTAKING_SUCCESS';
export const ADD_STOCKTAKING_FAILURE = 'PAGES/STOCKTAKING/ADD/ADD_STOCKTAKING_FAILURE';

//根据物品id获取物品信息
export const FETCH_STOCKTAKING_BY_ID_REQUEST = 'PAGES/STOCKTAKING/ADD/FETCH_STOCKTAKING_BY_ID_REQUEST';
export const FETCH_STOCKTAKING_BY_ID_SUCCESS = 'PAGES/STOCKTAKING/ADD/FETCH_STOCKTAKING_BY_ID_SUCCESS';
export const FETCH_STOCKTAKING_BY_ID_FAILURE = 'PAGES/STOCKTAKING/ADD/FETCH_STOCKTAKING_BY_ID_FAILURE';

// 结束盘点
export const CANCEL_STOCKTAKING_REQUEST = 'CANCEL_STOCKTAKING_REQUEST';
export const CANCEL_STOCKTAKING_SUCCESS = 'CANCEL_STOCKTAKING_SUCCESS';
export const CANCEL_STOCKTAKING_FAILURE = 'CANCEL_STOCKTAKING_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/STOCKTAKING/ADD/EMPTY_DETAIL_DATA';

export const MODIFY_STOCKTAKING_PROD_DATA = 'PAGES/STOCKTAKING/MODIFY_STOCKTAKING_PROD_DATA';




