//获取收支列表
export const FETCH_RATE_LIST_REQUEST = 'FETCH_RATE_LIST_REQUEST';
export const FETCH_RATE_LIST_SUCCESS = 'FETCH_RATE_LIST_SUCCESS';
export const FETCH_RATE_LIST_FAILURE = 'FETCH_RATE_LIST_FAILURE';

//新增/修改/删除收支提交
export const ADD_RATE_REQUEST = 'ADD_RATE_REQUEST';
export const ADD_RATE_SUCCESS = 'ADD_RATE_SUCCESS';
export const ADD_RATE_FAILURE = 'ADD_RATE_FAILURE';
