export const TYPE = 'SUPPLIER';
// 获取字段配置
export const FETCH_SUPPLIER_CONFIG_SUCCESS = "FETCH_SUPPLIER_CONFIG_SUCCESS";

// 获取供应商列表
export const SUPPLIER_LIST = 'SUPPLIER_LIST';
export const SUPPLIER_LIST_SUCCESS = 'SUPPLIER_LIST_SUCCESS';
export const SUPPLIER_LIST_FAILURE = 'SUPPLIER_LIST_FAILURE';

export const GET_LOCAL_SUPPLIER_INFO = 'GET_LOCAL_SUPPLIER_INFO';

export const SUPPLIER_CONFIRM_FETCHING_TRUE = 'SUPPLIER_CONFIRM_FETCHING_TRUE';
export const SUPPLIER_CONFIRM_FETCHING_FALSE = 'SUPPLIER_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const SUPPLIER_UPDATE_CONFIG = 'SUPPLIER_UPDATE_CONFIG';

//根据输入值联想供应商
export const FETCH_SUPPLIER_BY_VAL_REQUEST = 'SUPPLIER/INDEX/FETCH_SUPPLIER_BY_VAL_REQUEST';
export const FETCH_SUPPLIER_BY_VAL_SUCCESS = 'SUPPLIER/INDEX/FETCH_SUPPLIER_BY_VAL_SUCCESS';
export const FETCH_SUPPLIER_BY_VAL_FAILURE = 'SUPPLIER/INDEX/FETCH_SUPPLIER_BY_VAL_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/SUPPLIER/INDEX/FILTER_CONFIG_LIST';