export const TYPE = 'INQUIRY';
// 获取字段配置
export const FETCH_INQUIRY_CONFIG_SUCCESS = "FETCH_INQUIRY_CONFIG_SUCCESS";

// 获取询价列表
export const INQUIRY_LIST = 'INQUIRY_LIST';
export const INQUIRY_LIST_SUCCESS = 'INQUIRY_LIST_SUCCESS';
export const INQUIRY_LIST_FAILURE = 'INQUIRY_LIST_FAILURE';

// 获取询价单的报价列表
export const QUOTE_LIST = 'QUOTE_LIST';
export const QUOTE_LIST_SUCCESS = 'QUOTE_LIST_SUCCESS';
export const QUOTE_LIST_FAILURE = 'QUOTE_LIST_FAILURE';

export const GET_LOCAL_INQUIRY_INFO = 'GET_LOCAL_INQUIRY_INFO';

export const INQUIRY_CONFIRM_FETCHING_TRUE = 'INQUIRY_CONFIRM_FETCHING_TRUE';
export const INQUIRY_CONFIRM_FETCHING_FALSE = 'INQUIRY_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const INQUIRY_UPDATE_CONFIG = 'INQUIRY_UPDATE_CONFIG';

export const FETCH_INQUIRY_DETAIL = 'FETCH_INQUIRY_DETAIL';
export const FETCH_INQUIRY_DETAIL_SUCCESS = 'FETCH_INQUIRY_DETAIL_SUCCESS';
export const FETCH_INQUIRY_DETAIL_FAILURE = 'FETCH_INQUIRY_DETAIL_FAILURE';
