export const TYPE = 'INBOUND';
// 获取字段配置
export const FETCH_INBOUND_ORDER_CONFIG_SUCCESS = "FETCH_INBOUND_ORDER_CONFIG_SUCCESS";

// 获取入库单列表
export const INBOUND_ORDER_LIST = 'INBOUND_ORDER_LIST';
export const INBOUND_ORDER_LIST_SUCCESS = 'INBOUND_ORDER_LIST_SUCCESS';
export const INBOUND_ORDER_LIST_FAILURE = 'INBOUND_ORDER_LIST_FAILURE';

export const GET_LOCAL_INBOUND_ORDER_INFO = 'GET_LOCAL_INBOUND_ORDER_INFO';

export const INBOUND_ORDER_CONFIRM_FETCHING_TRUE = 'INBOUND_ORDER_CONFIRM_FETCHING_TRUE';
export const INBOUND_ORDER_CONFIRM_FETCHING_FALSE = 'INBOUND_ORDER_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const INBOUND_ORDER_UPDATE_CONFIG = 'INBOUND_ORDER_UPDATE_CONFIG';

// 获取入库记录
export const FETCH_INBOUND_RECORD_REQUEST = 'PAGES/INBOUND/INDEX/FETCH_INBOUND_RECORD_REQUEST';
export const FETCH_INBOUND_RECORD_SUCCESS = 'PAGES/INBOUND/INDEX/FETCH_INBOUND_RECORD_SUCCESS';
export const FETCH_INBOUND_RECORD_FAILURE = 'PAGES/INBOUND/INDEX/FETCH_INBOUND_RECORD_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'PAGES/INBOUND/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'PAGES/INBOUND/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'PAGES/INBOUND/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/INBOUND/INDEX/FILTER_CONFIG_LIST';