export const TYPE = 'PRODUCT_CONTROL';

// 获取字段配置
export const FETCH_PRODUCT_CONTROL_CONFIG_SUCCESS = "PAGES/PRODUCT_CONTROL/INDEX/FETCH_PRODUCT_CONTROL_CONFIG_SUCCESS";

export const FETCH_PRODUCT_CONTROL_LIST_REQUEST = 'PAGES/PRODUCT_CONTROL/INDEX/FETCH_PRODUCT_CONTROL_LIST_REQUEST';
export const FETCH_PRODUCT_CONTROL_LIST_SUCCESS = 'PAGES/PRODUCT_CONTROL/INDEX/FETCH_PRODUCT_CONTROL_LIST_SUCCESS';
export const FETCH_PRODUCT_CONTROL_LIST_FAILURE = 'PAGES/PRODUCT_CONTROL/INDEX/FETCH_PRODUCT_CONTROL_LIST_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/PRODUCT_CONTROL/INDEX/FILTER_CONFIG_LIST';
