//获取收支列表
export const FETCH_BILL_LIST_REQUEST = 'FETCH_BILL_LIST_REQUEST';
export const FETCH_BILL_LIST_SUCCESS = 'FETCH_BILL_LIST_SUCCESS';
export const FETCH_BILL_LIST_FAILURE = 'FETCH_BILL_LIST_FAILURE';

//新增/修改/删除收支提交
export const ADD_BILL_REQUEST = 'ADD_BILL_REQUEST';
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS';
export const ADD_BILL_FAILURE = 'ADD_BILL_FAILURE';
