//获取生产BOM详情
export const FETCH_MULTI_BOM_DETAIL_REQUEST = 'FETCH_MULTI_BOM_DETAIL_REQUEST';
export const FETCH_MULTI_BOM_DETAIL_SUCCESS = 'FETCH_MULTI_BOM_DETAIL_SUCCESS';
export const FETCH_MULTI_BOM_DETAIL_FAILURE = 'FETCH_MULTI_BOM_DETAIL_FAILURE';