//Mrp列表
export const FETCH_MRP_COUNT_LIST_REQUEST = 'FETCH_MRP_COUNT_LIST_REQUEST';
export const FETCH_MRP_COUNT_LIST_SUCCESS = 'FETCH_MRP_COUNT_LIST_SUCCESS';
export const FETCH_MRP_COUNT_LIST_FAILURE = 'FETCH_MRP_COUNT_LIST_FAILURE';

