//根据物品id获取物品信息
export const FETCH_SALE_BY_ID_REQUEST = 'COMPONENTS/BUSINESS/COPY_FROM_SALE/FETCH_SALE_BY_ID_REQUEST';
export const FETCH_SALE_BY_ID_SUCCESS = 'COMPONENTS/BUSINESS/COPY_FROM_SALE/FETCH_SALE_BY_ID_SUCCESS';
export const FETCH_SALE_BY_ID_FAILURE = 'COMPONENTS/BUSINESS/COPY_FROM_SALE/FETCH_SALE_BY_ID_FAILURE';


