export const TYPE = 'PURCHASE';

// 获取字段配置
export const FETCH_PURCHASE_CONFIG_SUCCESS = "PAGES/PURCHASE/INDEX/FETCH_PURCHASE_CONFIG_SUCCESS";

// 获取物品列表
export const PURCHASE_LIST = 'PAGES/PURCHASE/INDEX/PURCHASE_LIST';
/*export const PURCHASE_LIST_SUCCESS = 'PAGES/PURCHASE/INDEX/PURCHASE_LIST_SUCCESS';
export const PURCHASE_LIST_FAILURE = 'PAGES/PURCHASE/INDEX/PURCHASE_LIST_FAILURE';*/

export const GET_LOCAL_PURCHASE_INFO = 'PAGES/PURCHASE/INDEX/GET_LOCAL_PURCHASE_INFO';

export const PURCHASE_CONFIRM_FETCHING_TRUE = 'PAGES/PURCHASE/INDEX/PURCHASE_CONFIRM_FETCHING_TRUE';
export const PURCHASE_CONFIRM_FETCHING_FALSE = 'PAGES/PURCHASE/INDEX/PURCHASE_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const PURCHASE_UPDATE_CONFIG = 'PAGES/PURCHASE/INDEX/PURCHASE_UPDATE_CONFIG';

// 根据物品code获取物品仓库数量
export const FETCH_WARE_BY_CODE_REQUEST = 'PAGES/PURCHASE/INDEX/FETCH_WARE_BY_CODE_REQUEST';
export const FETCH_WARE_BY_CODE_SUCCESS = 'PAGES/PURCHASE/INDEX/FETCH_WARE_BY_CODE_SUCCESS';
export const FETCH_WARE_BY_CODE_FAILURE = 'PAGES/PURCHASE/INDEX/FETCH_WARE_BY_CODE_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'PAGES/PURCHASE/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'PAGES/PURCHASE/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'PAGES/PURCHASE/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 获取采购记录
export const FETCH_PURCHASE_RECORD_REQUEST = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_RECORD_REQUEST';
export const FETCH_PURCHASE_RECORD_SUCCESS = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_RECORD_SUCCESS';
export const FETCH_PURCHASE_RECORD_FAILURE = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_RECORD_FAILURE';

// 获取采购批量入库信息
export const FETCH_PURCHASE_BATCH_ENTER_INFO_REQUEST = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_ENTER_INFO_REQUEST';
export const FETCH_PURCHASE_BATCH_ENTER_INFO_SUCCESS = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_ENTER_INFO_SUCCESS';
export const FETCH_PURCHASE_BATCH_ENTER_INFO_FAILURE = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_ENTER_INFO_FAILURE';

// 获取采购订单批量付款信息，（待付款信息）
export const FETCH_PURCHASE_BATCH_PRE_EXPEND_REQUEST = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_PRE_EXPEND_REQUEST';
export const FETCH_PURCHASE_BATCH_PRE_EXPEND_SUCCESS = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_PRE_EXPEND_SUCCESS';
export const FETCH_PURCHASE_BATCH_PRE_EXPEND_FAILURE = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_PRE_EXPEND_FAILURE';

// 获取采购订单批量到票信息
export const FETCH_PURCHASE_BATCH_PRE_INVOICE_REQUEST = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_PRE_INVOICE_REQUEST';
export const FETCH_PURCHASE_BATCH_PRE_INVOICE_SUCCESS = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_PRE_INVOICE_SUCCESS';
export const FETCH_PURCHASE_BATCH_PRE_INVOICE_FAILURE = 'PAGES/PURCHASE/INDEX/FETCH_PURCHASE_BATCH_PRE_INVOICE_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/PURCHASE/INDEX/FILTER_CONFIG_LIST';
