export const TYPE = 'REPORT_INVENTORY';
// 获取物品列表
export const FETCH_REPORT_INVENTORY_DETAIL = 'FETCH_REPORT_INVENTORY_DETAIL';
export const FETCH_REPORT_INVENTORY_DETAIL_SUCCESS = 'FETCH_REPORT_INVENTORY_DETAIL_SUCCESS';
export const FETCH_REPORT_INVENTORY_DETAIL_FAILURE = 'FETCH_REPORT_INVENTORY_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_INVENTORY_DETAIL_UPDATE_CONFIG = 'REPORT_INVENTORY_DETAIL_UPDATE_CONFIG';

export const FETCH_BUSINESS_TYPE = 'FETCH_BUSINESS_TYPE';