//根据物品id获取物品信息
// export const FETCH_GOODS_BY_ID_REQUEST = 'GOODS/DETAIL/FETCH_GOODS_BY_ID_REQUEST';
// export const FETCH_GOODS_BY_ID_SUCCESS = 'GOODS/DETAIL/FETCH_GOODS_BY_ID_SUCCESS';
// export const FETCH_GOODS_BY_ID_FAILURE = 'GOODS/DETAIL/FETCH_GOODS_BY_ID_FAILURE';

export const RESET_GOODS_INFO = 'GOODS_RESET';

//获取操作日志
export const ASYNC_FETCH_OPERATION_LOG_REQUEST = 'PAGES/INVOICE/ADD/ASYNC_FETCH_OPERATION_LOG_REQUEST';
export const ASYNC_FETCH_OPERATION_LOG_SUCCESS = 'PAGES/INVOICE/ADD/ASYNC_FETCH_OPERATION_LOG_SUCCESS';
export const ASYNC_FETCH_OPERATION_LOG_FAILURE = 'PAGES/INVOICE/ADD/ASYNC_FETCH_OPERATION_LOG_FAILURE';