
export const FETCH_SUPPLIER_QUOTATION_RECORD_REQUEST = 'GOODS/DETAIL/FETCH_SUPPLIER_QUOTATION_RECORD_REQUEST';
export const FETCH_SUPPLIER_QUOTATION_RECORD_SUCCESS = 'GOODS/DETAIL/FETCH_SUPPLIER_QUOTATION_RECORD_SUCCESS';
export const FETCH_SUPPLIER_QUOTATION_RECORD_FAILURE = 'GOODS/DETAIL/FETCH_SUPPLIER_QUOTATION_RECORD_FAILURE';

