// 获取客户列表

export const TYPE = 'FINANCE_EXPAND';

export const EXPAND_LIST = 'EXPAND_LIST';
export const EXPAND_LIST_SUCCESS = 'EXPAND_LIST_SUCCESS';
export const EXPAND_LIST_FAILURE = 'EXPAND_LIST_FAILURE';

// 获取付款记录
export const FETCH_EXPEND_RECORD_REQUEST = 'FETCH_EXPEND_RECORD_REQUEST';
export const FETCH_EXPEND_RECORD_SUCCESS = 'FETCH_EXPEND_RECORD_SUCCESS';
export const FETCH_EXPEND_RECORD_FAILURE = 'FETCH_EXPEND_RECORD_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/FINANCE/EXPEND/INDEX/FILTER_CONFIG_LIST';

