
//获取页面初始数据
export const FETCH_OUTBOUND_PRE_DATA_REQUEST = 'FETCH_OUTBOUND_PRE_DATA_REQUEST';
export const FETCH_OUTBOUND_PRE_DATA_SUCCESS = 'FETCH_OUTBOUND_PRE_DATA_SUCCESS';
export const FETCH_OUTBOUND_PRE_DATA_FAILURE = 'FETCH_OUTBOUND_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_SALE_REQUEST = 'SALE/ADD/ADD_SALE_REQUEST';
export const ADD_SALE_SUCCESS = 'SALE/ADD/ADD_SALE_SUCCESS';
export const ADD_SALE_FAILURE = 'SALE/ADD/ADD_SALE_FAILURE';

// 查看详情
export const FETCH_DETAIL_BY_OUTBOUND_ID_REQUEST = 'FETCH_DETAIL_BY_OUTBOUND_ID_REQUEST';
export const FETCH_DETAIL_BY_OUTBOUND_ID_SUCCESS = 'FETCH_DETAIL_BY_OUTBOUND_ID_SUCCESS';
export const FETCH_DETAIL_BY_OUTBOUND_ID_FAILURE = 'FETCH_DETAIL_BY_OUTBOUND_ID_FAILURE';
