//生产工序列表
export const FETCH_WORKPROCEDURE_LIST_REQUEST = 'FETCH_WORKPROCEDURE_LIST_REQUEST';
export const FETCH_WORKPROCEDURE_LIST_SUCCESS = 'FETCH_WORKPROCEDURE_LIST_SUCCESS';
export const FETCH_WORKPROCEDURE_LIST_FAILURE = 'FETCH_WORKPROCEDURE_LIST_FAILURE';

//新增/修改/删除生产工序
export const ADD_WORKPROCEDURE_REQUEST = 'ADD_WORKPROCEDURE_REQUEST';
export const ADD_WORKPROCEDURE_SUCCESS = 'ADD_WORKPROCEDURE_SUCCESS';
export const ADD_WORKPROCEDURE_FAILURE = 'ADD_WORKPROCEDURE_FAILURE';
