export const TYPE = 'REPORT_GROSS_PROFIT';
// 获取物品列表
export const FETCH_REPORT_GROSS_PROFIT_DETAIL = 'FETCH_REPORT_GROSS_PROFIT_DETAIL';
export const FETCH_REPORT_GROSS_PROFIT_DETAIL_SUCCESS = 'FETCH_REPORT_GROSS_PROFIT_DETAIL_SUCCESS';
export const FETCH_REPORT_GROSS_PROFIT_DETAIL_FAILURE = 'FETCH_REPORT_GROSS_PROFIT_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_GROSS_PROFIT_DETAIL_UPDATE_CONFIG = 'REPORT_GROSS_PROFIT_DETAIL_UPDATE_CONFIG';

