//获取员工列表
export const FETCH_EMPLOYEE_LIST_REQUEST = 'FETCH_EMPLOYEE_LIST_REQUEST';
export const FETCH_EMPLOYEE_LIST_SUCCESS = 'FETCH_EMPLOYEE_LIST_SUCCESS';
export const FETCH_EMPLOYEE_LIST_FAILURE = 'FETCH_EMPLOYEE_LIST_FAILURE';

//新增/修改/删除员工提交
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';


export const VISIBLE_EMPLOYEE_REQUEST = 'VISIBLE_EMPLOYEE_REQUEST';
export const VISIBLE_EMPLOYEE_SUCCESS = 'VISIBLE_EMPLOYEE_SUCCESS';
export const VISIBLE_EMPLOYEE_FAILURE = 'VISIBLE_EMPLOYEE_FAILURE';