//生产BOM列表
export const FETCH_MULTI_BOM_LIST_REQUEST = 'FETCH_MULTI_BOM_LIST_REQUEST';
export const FETCH_MULTI_BOM_LIST_SUCCESS = 'FETCH_MULTI_BOM_LIST_SUCCESS';
export const FETCH_MULTI_BOM_LIST_FAILURE = 'FETCH_MULTI_BOM_LIST_FAILURE';
export const SET_MULTI_BOM_QUANTITY = 'SET_MULTI_BOM_QUANTITY';
export const SET_MULTI_BOM_LEVEL = 'SET_MULTI_BOM_LEVEL';
