
export const FETCH_COOPERATOR_LIST_DETAIL = 'FETCH_COOPERATOR_LIST_DETAIL';
export const FETCH_COOPERATOR_LIST_SUCCESS = 'FETCH_COOPERATOR_LIST_SUCCESS';
export const FETCH_COOPERATOR_LIST_FAILURE = 'FETCH_COOPERATOR_LIST_FAILURE';



