# server config
domainUrl: "love-and-peace.top"
appName: "gzy前端模板"
version: "1.0.0"
clientType: "PC_WEB"
title: "gzy前端模板"
clusters: false
port: 5000
devMode: true
logLevel: "INFO"
logDist: "c:\\log"


backendUrl: "http://10.110.1.185:8050"
cdBackendUrl: "http://cd.abiz.com"
cnMobileBackendUrl: "http://10.110.1.79:7088"
abizBackendUrl: "http://192.168.1.46:8081"
tulipBackendUrl: "http://192.168.0.155:8989"
voBackendUrl: "http://192.168.0.178:7002"
socketTimeout: 60000
fileSocketTimeout: 180000
cdn: ""
encoding: "utf8"
