//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/SCHEDULING/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/SCHEDULING/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/SCHEDULING/ADD/FETCH_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_SCHEDULING_REQUEST = 'PAGES/SCHEDULING/ADD/ADD_SCHEDULING_REQUEST';
export const ADD_SCHEDULING_SUCCESS = 'PAGES/SCHEDULING/ADD/ADD_SCHEDULING_SUCCESS';
export const ADD_SCHEDULING_FAILURE = 'PAGES/SCHEDULING/ADD/ADD_SCHEDULING_FAILURE';

//根据物品id获取物品信息
export const FETCH_SCHEDULING_BY_ID_REQUEST = 'PAGES/SCHEDULING/ADD/FETCH_SCHEDULING_BY_ID_REQUEST';
export const FETCH_SCHEDULING_BY_ID_SUCCESS = 'PAGES/SCHEDULING/ADD/FETCH_SCHEDULING_BY_ID_SUCCESS';
export const FETCH_SCHEDULING_BY_ID_FAILURE = 'PAGES/SCHEDULING/ADD/FETCH_SCHEDULING_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/SCHEDULING/ADD/EMPTY_DETAIL_DATA';




