//根据物品id获取物品信息
export const FETCH_SALE_BY_ID_REQUEST = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_SALE_BY_ID_REQUEST';
export const FETCH_SALE_BY_ID_SUCCESS = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_SALE_BY_ID_SUCCESS';
export const FETCH_SALE_BY_ID_FAILURE = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_SALE_BY_ID_FAILURE';

// 获取出库记录
export const FETCH_OUTBOUND_RECORD_REQUEST = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_OUTBOUND_RECORD_REQUEST';
export const FETCH_OUTBOUND_RECORD_SUCCESS = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_OUTBOUND_RECORD_SUCCESS';
export const FETCH_OUTBOUND_RECORD_FAILURE = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_OUTBOUND_RECORD_FAILURE';


// 获取付款记录
export const FETCH_INCOME_RECORD_REQUEST = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_INCOME_RECORD_REQUEST';
export const FETCH_INCOME_RECORD_SUCCESS = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_INCOME_RECORD_SUCCESS';
export const FETCH_INCOME_RECORD_FAILURE = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_INCOME_RECORD_FAILURE';


export const FETCH_SALEINVOICE_RECORD_REQUEST = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_SALEINVOICE_RECORD_REQUEST';
export const FETCH_SALEINVOICE_RECORD_SUCCESS = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_SALEINVOICE_RECORD_SUCCESS';
export const FETCH_SALEINVOICE_RECORD_FAILURE = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_SALEINVOICE_RECORD_FAILURE';


export const FETCH_PRODUCE_RECORD_REQUEST = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_PRODUCE_RECORD_REQUEST';
export const FETCH_PRODUCE_RECORD_SUCCESS = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_PRODUCE_RECORD_SUCCESS';
export const FETCH_PRODUCE_RECORD_FAILURE = 'PAGES/ORDER_TRACK/SALE/SHOW/FETCH_PRODUCE_RECORD_FAILURE';