export const TYPE = 'REPORT_PURCHASE_SUMMARY_BY_SUPPLIER';
// 获取物品列表
export const FETCH_PURCHASE_SUMMARY_BY_SUPPLIER = 'PAGES/REPORT/FETCH_PURCHASE_SUMMARY_BY_SUPPLIER';

// 更新配置字段
export const REPORT_PURCHASE_SUMMARY_BY_SUPPLIER_DETAIL_UPDATE_CONFIG = 'REPORT_PURCHASE_SUMMARY_BY_SUPPLIER_DETAIL_UPDATE_CONFIG';

