export const TYPE = 'REQUISITION_APPLY_ORDER';

// 获取字段配置
export const FETCH_REQUISITION_APPLY_ORDER_CONFIG_SUCCESS = "FETCH_REQUISITION_APPLY_ORDER_CONFIG_SUCCESS";

//获取采购申请明细列表数据
export const FETCH_REQUISITION_APPLY_ORDER_LIST_REQUEST = 'FETCH_REQUISITION_APPLY_ORDER_LIST_REQUEST';
export const FETCH_REQUISITION_APPLY_ORDER_LIST_SUCCESS = 'FETCH_REQUISITION_APPLY_ORDER_LIST_SUCCESS';
export const FETCH_REQUISITION_APPLY_ORDER_LIST_FAILURE = 'FETCH_REQUISITION_APPLY_ORDER_LIST_FAILURE';


// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/REQUISITION_APPLY_ORDER/INDEX/FILTER_CONFIG_LIST';



