//发送给供应商
export const FETCH_SUBCONTRACT_DETAIL_BY_ID_REQUEST = 'FETCH_SUBCONTRACT_DETAIL_BY_ID_REQUEST';
export const FETCH_SUBCONTRACT_DETAIL_BY_ID_SUCCESS = 'FETCH_SUBCONTRACT_DETAIL_BY_ID_SUCCESS';
export const FETCH_SUBCONTRACT_DETAIL_BY_ID_FAILURE = 'FETCH_SUBCONTRACT_DETAIL_BY_ID_FAILURE';


export const FETCH_GENERATE_OUT_REQUEST = 'FETCH_GENERATE_OUT_REQUEST';
export const FETCH_GENERATE_OUT_SUCCESS = 'FETCH_GENERATE_OUT_SUCCESS';
export const FETCH_GENERATE_OUT_FAILURE = 'FETCH_GENERATE_OUT_FAILURE';

export const FETCH_GENERATE_IN_REQUEST = 'FETCH_GENERATE_IN_REQUEST';
export const FETCH_GENERATE_IN_SUCCESS = 'FETCH_GENERATE_IN_SUCCESS';
export const FETCH_GENERATE_IN_FAILURE = 'FETCH_GENERATE_IN_FAILURE';