export const TYPE = 'REPORT_PURCHASE_SUMMARY';
// 获取物品列表
export const FETCH_PURCHASE_SUMMARY_BY_PROD = 'PAGES/REPORT/FETCH_PURCHASE_SUMMARY_BY_PROD';

// 更新配置字段
export const REPORT_PURCHASE_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG = 'REPORT_PURCHASE_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG';

