//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PRE_DATA_FAILURE';

//新增工单提交
export const ADD_PRODUCT_CONTROL_REQUEST = 'PAGES/PRODUCT_CONTROL/ADD/ADD_PRODUCT_CONTROL_REQUEST';
export const ADD_PRODUCT_CONTROL_SUCCESS = 'PAGES/PRODUCT_CONTROL/ADD/ADD_PRODUCT_CONTROL_SUCCESS';
export const ADD_PRODUCT_CONTROL_FAILURE = 'PAGES/PRODUCT_CONTROL/ADD/ADD_PRODUCT_CONTROL_FAILURE';

//根据物品id获取工单信息
export const FETCH_PRODUCT_CONTROL_BY_ID_REQUEST = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PRODUCT_CONTROL_BY_ID_REQUEST';
export const FETCH_PRODUCT_CONTROL_BY_ID_SUCCESS = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PRODUCT_CONTROL_BY_ID_SUCCESS';
export const FETCH_PRODUCT_CONTROL_BY_ID_FAILURE = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PRODUCT_CONTROL_BY_ID_FAILURE';

export const FETCH_PROCESS_LIST_REQUEST = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PROCESS_LIST_REQUEST';
export const FETCH_PROCESS_LIST_SUCCESS = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PROCESS_LIST_SUCCESS';
export const FETCH_PROCESS_LIST_FAILURE = 'PAGES/PRODUCT_CONTROL/ADD/FETCH_PROCESS_LIST_FAILURE';


//清空
export const EMPTY_DETAIL_DATA = 'PAGES/PRODUCT_CONTROL/ADD/EMPTY_DETAIL_DATA';




