//获取类目列表
export const FETCH_CATE_LIST_REQUEST = 'FETCH_CATE_LIST_REQUEST';
export const FETCH_CATE_LIST_SUCCESS = 'FETCH_CATE_LIST_SUCCESS';
export const FETCH_CATE_LIST_FAILURE = 'FETCH_CATE_LIST_FAILURE';

//新增/修改/删除类目提交
export const ADD_CATE_REQUEST = 'ADD_CATE_REQUEST';
export const ADD_CATE_SUCCESS = 'ADD_CATE_SUCCESS';
export const ADD_CATE_FAILURE = 'ADD_CATE_FAILURE';

export const EDIT_CATE_SUCCESS = 'EDIT_CATE_SUCCESS';

export const DEL_CATE_SUCCESS = 'DEL_CATE_SUCCESS';
