//工作中心列表
export const FETCH_WORKCENTER_LIST_REQUEST = 'FETCH_WORKCENTER_LIST_REQUEST';
export const FETCH_WORKCENTER_LIST_SUCCESS = 'FETCH_WORKCENTER_LIST_SUCCESS';
export const FETCH_WORKCENTER_LIST_FAILURE = 'FETCH_WORKCENTER_LIST_FAILURE';

//新增/修改/删除工作中心
export const ADD_WORKCENTER_REQUEST = 'ADD_WORKCENTER_REQUEST';
export const ADD_WORKCENTER_SUCCESS = 'ADD_WORKCENTER_SUCCESS';
export const ADD_WORKCENTER_FAILURE = 'ADD_WORKCENTER_FAILURE';

export const ASYNC_FETCH_WORK_CENTER_DETAIL = 'ASYNC_FETCH_WORK_CENTER_DETAIL';