export const TYPE = 'REPORT_SALE_SUMMARY_BY_PROD';
// 获取物品列表
export const FETCH_SALE_SUMMARY_BY_PROD = 'PAGES/REPORT/FETCH_SALE_SUMMARY_BY_PROD';

// 更新配置字段
export const REPORT_SALE_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG = 'REPORT_SALE_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG';

