
export const FETCH_REPORT_SALE_SUMMARY_DETAIL = 'REPORT_SALE_SUMMARY_DETAIL';
export const FETCH_REPORT_SALE_SUMMARY_DETAIL_SUCCESS = 'REPORT_SALE_SUMMARY_DETAIL_SUCCESS';
export const FETCH_REPORT_SALE_SUMMARY_DETAIL_FAILURE = 'REPORT_SALE_SUMMARY_DETAIL_FAILURE';


