//CN物品列表
export const FETCH_AUTO_IMPORT_REQUEST = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/FETCH_AUTO_IMPORT_REQUEST';
export const FETCH_AUTO_IMPORT_SUCCESS = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/FETCH_AUTO_IMPORT_SUCCESS';
export const FETCH_AUTO_IMPORT_FAILURE = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/FETCH_AUTO_IMPORT_FAILURE';

