//获取审批列表
export const FETCH_APPROVE_LIST_REQUEST = 'FETCH_APPROVE_LIST_REQUEST';
export const FETCH_APPROVE_LIST_SUCCESS = 'FETCH_APPROVE_LIST_SUCCESS';
export const FETCH_APPROVE_LIST_FAILURE = 'FETCH_APPROVE_LIST_FAILURE';

//检查业务单据是否已全部审核
export const CHECK_APPROVE_REQUEST = 'CHECK_APPROVE_REQUEST';
export const CHECK_APPROVE_SUCCESS = 'CHECK_APPROVE_SUCCESS';
export const CHECK_APPROVE_FAILURE = 'CHECK_APPROVE_FAILURE';

//启用/停用审批
export const TOGGLE_ENABLE_REQUEST = 'TOGGLE_ENABLE_REQUEST';
export const TOGGLE_ENABLE_SUCCESS = 'TOGGLE_ENABLE_SUCCESS';
export const TOGGLE_ENABLE_FAILURE = 'TOGGLE_ENABLE_FAILURE';
