//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/MULTI_BOM/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/MULTI_BOM/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/MULTI_BOM/ADD/FETCH_PRE_DATA_FAILURE';

//新增多级BOM提交
export const ADD_MULTI_BOM_REQUEST = 'PAGES/MULTI_BOM/ADD/ADD_MULTI_BOM_REQUEST';
export const ADD_MULTI_BOM_SUCCESS = 'PAGES/MULTI_BOM/ADD/ADD_MULTI_BOM_SUCCESS';
export const ADD_MULTI_BOM_FAILURE = 'PAGES/MULTI_BOM/ADD/ADD_MULTI_BOM_FAILURE';

// 根据物品id获取多级BOM信息
export const FETCH_MULTI_BOM_BY_ID_REQUEST = 'PAGES/MULTI_BOM/ADD/FETCH_MULTI_BOM_BY_ID_REQUEST';
export const FETCH_MULTI_BOM_BY_ID_SUCCESS = 'PAGES/MULTI_BOM/ADD/FETCH_MULTI_BOM_BY_ID_SUCCESS';
export const FETCH_MULTI_BOM_BY_ID_FAILURE = 'PAGES/MULTI_BOM/ADD/FETCH_MULTI_BOM_BY_ID_FAILURE';

// 根据bomCode获取多级BOM信息
export const ASYNC_FETCH_WORK_SHEET_RECORD_BY_CODE = 'PAGES/MULTI_BOM/ADD/FETCH_MULTI_BOM_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/MULTI_BOM/ADD/EMPTY_DETAIL_DATA';




