export const TYPE = 'REPORT_PRODUCE_PERFORMANCE';
//生产绩效统计表
export const FETCH_REPORT_PRODUCE_PERFORMANCE_DETAIL = 'FETCH_REPORT_PRODUCE_PERFORMANCE_DETAIL';
export const FETCH_REPORT_PRODUCE_PERFORMANCE_DETAIL_SUCCESS = 'FETCH_REPORT_PRODUCE_PERFORMANCE_DETAIL_SUCCESS';
export const FETCH_REPORT_PRODUCE_PERFORMANCE_DETAIL_FAILURE = 'FETCH_REPORT_PRODUCE_PERFORMANCE_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_REPORT_PRODUCE_DETAIL_UPDATE_CONFIG = 'REPORT_PURCHASE_TRACE_TRACE_DETAIL_UPDATE_CONFIG';

