export const TYPE = 'REPORT_QUOTATION';
// 获取物品列表
export const FETCH_REPORT_QUOTATION_DETAIL = 'FETCH_REPORT_QUOTATION_DETAIL';
export const FETCH_REPORT_QUOTATION_DETAIL_SUCCESS = 'FETCH_REPORT_QUOTATION_DETAIL_SUCCESS';
export const FETCH_REPORT_QUOTATION_DETAIL_FAILURE = 'FETCH_REPORT_QUOTATION_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_QUOTATION_DETAIL_UPDATE_CONFIG = 'REPORT_QUOTATION_DETAIL_UPDATE_CONFIG';

