export const TYPE = 'REPORT_GROSS_PROFIT_CUSTOMER';
// 获取客户毛利润统计表
export const FETCH_REPORT_GROSS_PROFIT_CUSTOMER_DETAIL = 'FETCH_REPORT_GROSS_PROFIT_CUSTOMER_DETAIL';
export const FETCH_REPORT_GROSS_PROFIT_CUSTOMER_DETAIL_SUCCESS = 'FETCH_REPORT_GROSS_PROFIT_CUSTOMER_DETAIL_SUCCESS';
export const FETCH_REPORT_GROSS_PROFIT_CUSTOMER_DETAIL_FAILURE = 'FETCH_REPORT_GROSS_PROFIT_CUSTOMER_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_GROSS_PROFIT_DETAIL_UPDATE_CONFIG = 'REPORT_GROSS_PROFIT_DETAIL_UPDATE_CONFIG';

