//获取部门下拉
export const FETCH_DEPT_EMP_REQUEST = 'FETCH_DEPT_EMP_REQUEST';
export const FETCH_DEPT_EMP_SUCCESS = 'FETCH_DEPT_EMP_SUCCESS';
export const FETCH_DEPT_EMP_FAILURE = 'FETCH_DEPT_EMP_FAILURE';

export const GET_EMPLOYEES_BY_DEPT_ID = 'GET_EMPLOYEES_BY_DEPT_ID';
export const GET_EMPLOYEES_BY_DEPT_ID_TYPE1 = 'GET_EMPLOYEES_BY_DEPT_ID_TYPE1';
export const GET_DEPT_AND_EMPLOYEES_BY_EMPLOYEE_ID = 'GET_DEPT_AND_EMPLOYEES_BY_EMPLOYEE_ID';
export const EMPTY_DEPT_EMPLOYEE = 'EMPTY_DEPT_EMPLOYEE';

//获取部门列表
export const FETCH_DEPT_LIST_REQUEST = 'FETCH_DEPT_LIST_REQUEST';
export const FETCH_DEPT_LIST_SUCCESS = 'FETCH_DEPT_LIST_SUCCESS';
export const FETCH_DEPT_LIST_FAILURE = 'FETCH_DEPT_LIST_FAILURE';

//新增/修改/删除部门提交
export const ADD_DEPT_REQUEST = 'ADD_DEPT_REQUEST';
export const ADD_DEPT_SUCCESS = 'ADD_DEPT_SUCCESS';
export const ADD_DEPT_FAILURE = 'ADD_DEPT_FAILURE';
