export const TYPE = 'OUTBOUND';
// 获取字段配置
export const FETCH_OUTBOUND_ORDER_CONFIG_SUCCESS = "FETCH_OUTBOUND_ORDER_CONFIG_SUCCESS";

// 获取出库单列表
export const OUTBOUND_ORDER_LIST = 'OUTBOUND_ORDER_LIST';
export const OUTBOUND_ORDER_LIST_SUCCESS = 'OUTBOUND_ORDER_LIST_SUCCESS';
export const OUTBOUND_ORDER_LIST_FAILURE = 'OUTBOUND_ORDER_LIST_FAILURE';

export const OUTBOUND_ORDER_CONFIRM_FETCHING_TRUE = 'OUTBOUND_ORDER_CONFIRM_FETCHING_TRUE';
export const OUTBOUND_ORDER_CONFIRM_FETCHING_FALSE = 'OUTBOUND_ORDER_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const OUTBOUND_ORDER_UPDATE_CONFIG = 'OUTBOUND_ORDER_UPDATE_CONFIG';

// 获取出库记录
export const FETCH_OUTBOUND_RECORD_REQUEST = 'PAGES/OUTBOUND/INDEX/FETCH_OUTBOUND_RECORD_REQUEST';
export const FETCH_OUTBOUND_RECORD_SUCCESS = 'PAGES/OUTBOUND/INDEX/FETCH_OUTBOUND_RECORD_SUCCESS';
export const FETCH_OUTBOUND_RECORD_FAILURE = 'PAGES/OUTBOUND/INDEX/FETCH_OUTBOUND_RECORD_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'PAGES/OUTBOUND/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'PAGES/OUTBOUND/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'PAGES/OUTBOUND/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

//操作日志
export const ASYNC_OPERATION_LOGS_SUCCESS = 'ASYNC_OPERATION_LOGS_SUCCESS';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/OUTBOUND/INDEX/FILTER_CONFIG_LIST';