// 获取字段配置
// export const FETCH_INCOME_CONFIG_SUCCESS = "FETCH_INCOME_CONFIG_SUCCESS";

export const TYPE = 'FINANCE_INCOME';
// 获取客户列表
export const INCOME_LIST = 'INCOME_LIST';
export const INCOME_LIST_SUCCESS = 'INCOME_LIST_SUCCESS';
export const INCOME_LIST_FAILURE = 'INCOME_LIST_FAILURE';

export const INCOME_CONFIRM_FETCHING_TRUE = 'INCOME_CONFIRM_FETCHING_TRUE';
export const INCOME_CONFIRM_FETCHING_FALSE = 'INCOME_CONFIRM_FETCHING_FALSE';

// 获取付款记录
export const FETCH_INCOME_RECORD_REQUEST = 'FETCH_INCOME_RECORD_REQUEST';
export const FETCH_INCOME_RECORD_SUCCESS = 'FETCH_INCOME_RECORD_SUCCESS';
export const FETCH_INCOME_RECORD_FAILURE = 'FETCH_INCOME_RECORD_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/FINANCE/INCOME/INDEX/FILTER_CONFIG_LIST';
