
//新增收入记录
export const ADD_INVOICE_REQUEST = 'ADD_INVOICE_REQUEST';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAILURE = 'ADD_INVOICE_FAILURE';

//根据物income id获取收入记录信息
export const FETCH_INVOICE_BY_ID_REQUEST = 'FETCH_INVOICE_BY_ID_REQUEST';
export const FETCH_INVOICE_BY_ID_SUCCESS = 'FETCH_INVOICE_BY_ID_SUCCESS';
export const FETCH_INVOICE_BY_ID_FAILURE = 'FETCH_INVOICE_BY_ID_FAILURE';

//获取收支列表
export const FETCH_INVOICE_LIST_REQUEST = 'FETCH_INVOICE_LIST_REQUEST';
export const FETCH_INVOICE_LIST_SUCCESS = 'FETCH_INVOICE_LIST_SUCCESS';
export const FETCH_INVOICE_LIST_FAILURE = 'FETCH_INVOICE_LIST_FAILURE';