export const FIELD_CHANGE = 'BUSINESS/LAYOUT/ADD_FORM/FIELD_CHANGE';
export const EMPTY_FIELD_CHANGE = 'BUSINESS/LAYOUT/ADD_FORM/EMPTY_FIELD_CHANGE';
export const SET_INIT_FINISHED = 'BUSINESS/LAYOUT/ADD_FORM/SET_INIT_FINISHED'
export const RESET_INIT_FINISHED = 'BUSINESS/LAYOUT/ADD_FORM/RESET_INIT_FINISHED';