// 取消在线销售订单请求
export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

// 接收在线销售订单请求
export const ACCEPT_ORDER_REQUEST = 'ACCEPT_ORDER_REQUEST';
export const ACCEPT_ORDER_SUCCESS = 'ACCEPT_ORDER_SUCCESS';
export const ACCEPT_ORDER_FAILURE = 'ACCEPT_ORDER_FAILURE';

// 一键转为我的物品
export const REQUEST_CONVERT_LOCAL_PROD = 'PAGES/SALE/DETAIL/REQUEST_CONVERT_LOCAL_PROD';
export const REQUEST_CONVERT_LOCAL_PROD_SUCCESS = 'PAGES/SALE/DETAIL/REQUEST_CONVERT_LOCAL_PROD_SUCCESS';
export const REQUEST_CONVERT_LOCAL_PROD_FAILED = 'PAGES/SALE/DETAIL/REQUEST_CONVERT_LOCAL_PROD_FAILED';
