
export const FETCH_SALE_AND_PRODUCT_PROGRESS_REQUEST = 'FETCH_SALE_AND_PRODUCT_PROGRESS_REQUEST';
export const FETCH_SALE_AND_PRODUCT_PROGRESS_SUCCESS = 'FETCH_SALE_AND_PRODUCT_PROGRESS_SUCCESS';
export const FETCH_SALE_AND_PRODUCT_PROGRESS_FAILURE = 'FETCH_SALE_AND_PRODUCT_PROGRESS_FAILURE';


