//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/SUBCONTRACT/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/SUBCONTRACT/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/SUBCONTRACT/ADD/FETCH_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_SUBCONTRACT_REQUEST = 'PAGES/SUBCONTRACT/ADD/ADD_SUBCONTRACT_REQUEST';
export const ADD_SUBCONTRACT_SUCCESS = 'PAGES/SUBCONTRACT/ADD/ADD_SUBCONTRACT_SUCCESS';
export const ADD_SUBCONTRACT_FAILURE = 'PAGES/SUBCONTRACT/ADD/ADD_SUBCONTRACT_FAILURE';

//根据物品id获取物品信息
export const FETCH_SUBCONTRACT_BY_ID_REQUEST = 'PAGES/SUBCONTRACT/ADD/FETCH_SUBCONTRACT_BY_ID_REQUEST';
export const FETCH_SUBCONTRACT_BY_ID_SUCCESS = 'PAGES/SUBCONTRACT/ADD/FETCH_SUBCONTRACT_BY_ID_SUCCESS';
export const FETCH_SUBCONTRACT_BY_ID_FAILURE = 'PAGES/SUBCONTRACT/ADD/FETCH_SUBCONTRACT_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/SUBCONTRACT/ADD/EMPTY_DETAIL_DATA';




