
//新增收入记录
export const ADD_INCOME_REQUEST = 'ADD_INCOME_REQUEST';
export const ADD_INCOME_SUCCESS = 'ADD_INCOME_SUCCESS';
export const ADD_INCOME_FAILURE = 'ADD_INCOME_FAILURE';

//根据物income id获取收入记录信息
export const FETCH_INCOME_BY_ID_REQUEST = 'FETCH_INCOME_BY_ID_REQUEST';
export const FETCH_INCOME_BY_ID_SUCCESS = 'FETCH_INCOME_BY_ID_SUCCESS';
export const FETCH_INCOME_BY_ID_FAILURE = 'FETCH_INCOME_BY_ID_FAILURE';

//获取收支列表
export const FETCH_INCOME_LIST_REQUEST = 'FETCH_INCOME_LIST_REQUEST';
export const FETCH_INCOME_LIST_SUCCESS = 'FETCH_INCOME_LIST_SUCCESS';
export const FETCH_INCOME_LIST_FAILURE = 'FETCH_INCOME_LIST_FAILURE';