export const TYPE = 'SCHEDULING';
// 获取字段配置
export const FETCH_SCHEDULING_CONFIG_SUCCESS = "FETCH_SCHEDULING_CONFIG_SUCCESS";

// 获取调拨单列表
export const SCHEDULING_LIST = 'SCHEDULING_LIST';
export const SCHEDULING_LIST_SUCCESS = 'SCHEDULING_LIST_SUCCESS';
export const SCHEDULING_LIST_FAILURE = 'SCHEDULING_LIST_FAILURE';

export const GET_LOCAL_SCHEDULING_INFO = 'GET_LOCAL_SCHEDULING_INFO';

export const SCHEDULING_CONFIRM_FETCHING_TRUE = 'SCHEDULING_CONFIRM_FETCHING_TRUE';
export const SCHEDULING_CONFIRM_FETCHING_FALSE = 'SCHEDULING_CONFIRM_FETCHING_FALSE';

// 更新配置字段
export const SCHEDULING_UPDATE_CONFIG = 'SCHEDULING_UPDATE_CONFIG';

//根据输入值联想客户
export const FETCH_SCHEDULING_BY_VAL_REQUEST = 'SCHEDULING/INDEX/FETCH_SCHEDULING_BY_VAL_REQUEST';
export const FETCH_SCHEDULING_BY_VAL_SUCCESS = 'SCHEDULING/INDEX/FETCH_SCHEDULING_BY_VAL_SUCCESS';
export const FETCH_SCHEDULING_BY_VAL_FAILURE = 'SCHEDULING/INDEX/FETCH_SCHEDULING_BY_VAL_FAILURE';

// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'SCHEDULING/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'SCHEDULING/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'SCHEDULING/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/SCHEDULING/INDEX/FILTER_CONFIG_LIST';