export const TYPE = 'REPORT_HISTORICAL_TRACE';

export const FETCH_HISTORICAL_TRACE = 'PAGES/REPORT/FETCH_HISTORICAL_TRACE';

// 更新配置字段
export const REPORT__HISTORICAL_TRACE_DETAIL_UPDATE_CONFIG = 'REPORT__HISTORICAL_TRACE_DETAIL_UPDATE_CONFIG';

