export const TYPE = 'REPORT_SALE_REFUND_SUMMARY_BY_PROD';
// 获取销售及退货汇总表列表
export const FETCH_SALE_REFUND_SUMMARY_BY_PROD = 'PAGES/REPORT/FETCH_SALE_REFUND_SUMMARY_BY_PROD';

// 更新配置字段
// export const FETCH_SALE_REFUND_SUMMARY_BY_PROD = 'REPORT_SALE_REFUND_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG';

