//多币种列表
export const FETCH_MULTI_CURRENCY_LIST_REQUEST = 'FETCH_MULTI_CURRENCY_LIST_REQUEST';
export const FETCH_MULTI_CURRENCY_LIST_SUCCESS = 'FETCH_MULTI_CURRENCY_LIST_SUCCESS';
export const FETCH_MULTI_CURRENCY_LIST_FAILURE = 'FETCH_MULTI_CURRENCY_LIST_FAILURE';

//新增/修改/删除多币种
export const ADD_MULTI_CURRENCY_REQUEST = 'ADD_MULTI_CURRENCY_REQUEST';
export const ADD_MULTI_CURRENCY_SUCCESS = 'ADD_MULTI_CURRENCY_SUCCESS';
export const ADD_MULTI_CURRENCY_FAILURE = 'ADD_MULTI_CURRENCY_FAILURE';


export const FETCH_CURRENCY_DETAIL_REQUEST = 'FETCH_CURRENCY_DETAIL_REQUEST';
export const FETCH_CURRENCY_DETAIL_SUCCESS = 'FETCH_CURRENCY_DETAIL_SUCCESS';
export const FETCH_CURRENCY_DETAIL_FAILURE = 'FETCH_CURRENCY_DETAIL_FAILURE';
