//CN物品列表
export const FETCH_CN_GOODS_LIST_REQUEST = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/FETCH_CN_GOODS_LIST_REQUEST';
export const FETCH_CN_GOODS_LIST_SUCCESS = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/FETCH_CN_GOODS_LIST_SUCCESS';
export const FETCH_CN_GOODS_LIST_FAILURE = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/FETCH_CN_GOODS_LIST_FAILURE';

//导入CN物品
export const IMPORT_CN_GOODS_REQUEST = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/IMPORT_CN_GOODS_REQUEST';
export const IMPORT_CN_GOODS_SUCCESS = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/IMPORT_CN_GOODS_SUCCESS';
export const IMPORT_CN_GOODS_FAILURE = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/IMPORT_CN_GOODS_FAILURE';

export const EMPTY_IMPORT_CN_GOODS = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/EMPTY_IMPORT_CN_GOODS';
export const IMPORT_CN_GOODS_PERCENT = 'COMPONENTS/BUSINESS/IMPORT_GOODS_POP/IMPORT_CN_GOODS_PERCENT';


