
export const FETCH_NEW_CUSTOM_FIELD_LIST_REQUEST = 'FETCH_NEW_CUSTOM_FIELD_LIST_REQUEST';
export const FETCH_NEW_CUSTOM_FIELD_LIST_SUCCESS = 'FETCH_NEW_CUSTOM_FIELD_LIST_SUCCESS';
export const FETCH_NEW_CUSTOM_FIELD_LIST_FAILURE = 'FETCH_NEW_CUSTOM_FIELD_LIST_FAILURE';


export const ADD_NEW_CUSTOM_FIELD_REQUEST = 'ADD_NEW_CUSTOM_FIELD_REQUEST';
export const ADD_NEW_CUSTOM_FIELD_SUCCESS = 'ADD_NEW_CUSTOM_FIELD_SUCCESS';
export const ADD_NEW_CUSTOM_FIELD_FAILURE = 'ADD_NEW_CUSTOM_FIELD_FAILURE';
