export const TYPE = 'REPORT_PURCHASE_REFUND_SUMMARY_BY_PROD';
// 获取采购及退货统计表列表
export const FETCH_PURCHASE_REFUND_SUMMARY_BY_PROD = 'PAGES/REPORT/FETCH_PURCHASE_REFUND_SUMMARY_BY_PROD';

// 更新配置字段
// export const FETCH_SALE_REFUND_SUMMARY_BY_PROD = 'REPORT_SALE_REFUND_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG';

