
export const TYPE = 'REPORT_CHECK_SUPPLIER';
// 获取物品列表
export const FETCH_REPORT_ORDERIN_DETAIL = 'REPORT_ORDERIN_DETAIL';
export const FETCH_REPORT_ORDERIN_DETAIL_SUCCESS = 'REPORT_ORDERIN_DETAIL_SUCCESS';
export const FETCH_REPORT_ORDERIN_DETAIL_FAILURE = 'REPORT_ORDERIN_DETAIL_FAILURE';


