//获取收支列表
export const FETCH_EXPRESS_LIST_REQUEST = 'FETCH_EXPRESS_LIST_REQUEST';
export const FETCH_EXPRESS_LIST_SUCCESS = 'FETCH_EXPRESS_LIST_SUCCESS';
export const FETCH_EXPRESS_LIST_FAILURE = 'FETCH_EXPRESS_LIST_FAILURE';

//新增/修改/删除收支提交
export const ADD_EXPRESS_REQUEST = 'ADD_EXPRESS_REQUEST';
export const ADD_EXPRESS_SUCCESS = 'ADD_EXPRESS_SUCCESS';
export const ADD_EXPRESS_FAILURE = 'ADD_EXPRESS_FAILURE';
