// 联系记录列表
export const CONTACT_RECORD_LIST = 'CONTACT_RECORD_LIST';
export const CONTACT_RECORD_LIST_SUCCESS = 'CONTACT_RECORD_LIST_SUCCESS';
export const CONTACT_RECORD_LIST_FAILURE = 'CONTACT_RECORD_LIST_FAILURE';

export const DEFAULT_CONTACT_RECORD_SUCCESS = 'DEFAULT_CONTACT_RECORD_SUCCESS';
export const DEFAULT_CONTACT_RECORD_FAILURE = 'DEFAULT_CONTACT_RECORD_FAILURE';

export const GET_LOCAL_CONTACT_RECORD_INFO = 'GET_LOCAL_CONTACT_RECORD_INFO';

export const CONTACT_RECORD_CONFIRM_FETCHING_TRUE = 'CONTACT_RECORD_CONFIRM_FETCHING_TRUE';
export const CONTACT_RECORD_CONFIRM_FETCHING_FALSE = 'CONTACT_RECORD_CONFIRM_FETCHING_FALSE';

