//新增删除物品条目
export const ADD_GOODS_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/ADD_GOODS_ITEM';
export const REMOVE_GOODS_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/REMOVE_GOODS_ITEM';
export const INIT_GOODS_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/INIT_GOODS_ITEM';
export const INIT_GOODS_DEFAULT_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/INIT_GOODS_DEFAULT_ITEM';

export const SET_FIELD_READONLY = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/SET_FIELD_READONLY';
export const UNSET_FIELD_READONLY = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/UNSET_FIELD_READONLY';

// 根据物品code获取物品库存信息
export const FETCH_STOCK_BY_CODE_REQUEST = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/FETCH_STOCK_BY_CODE_REQUEST';
export const FETCH_STOCK_BY_CODE_SUCCESS = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/FETCH_STOCK_BY_CODE_SUCCESS';
export const FETCH_STOCK_BY_CODE_FAILURE = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/FETCH_STOCK_BY_CODE_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/PREFORM/EMPTY_DETAIL_DATA';


