//新增删除物品条目
export const ADD_GOODS_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/ADD_GOODS_ITEM_OUT';
export const REMOVE_GOODS_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/REMOVE_GOODS_ITEM_OUT';
export const INIT_GOODS_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/INIT_GOODS_ITEM_OUT';
export const INIT_GOODS_DEFAULT_ITEM = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/INIT_GOODS_DEFAULT_ITEM_OUT';

export const SET_FIELD_READONLY = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/SET_FIELD_READONLY_OUT';
export const UNSET_FIELD_READONLY = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/UNSET_FIELD_READONLY_OUT';

// 根据物品code获取物品库存信息
export const FETCH_STOCK_BY_CODE_REQUEST = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/FETCH_STOCK_BY_CODE_REQUEST_OUT';
export const FETCH_STOCK_BY_CODE_SUCCESS = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/FETCH_STOCK_BY_CODE_SUCCESS_OUT';
export const FETCH_STOCK_BY_CODE_FAILURE = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/FETCH_STOCK_BY_CODE_FAILURE_OUT';

//清空
export const EMPTY_DETAIL_DATA = 'COMPONENTS/BUSINESS/SUBCONTRACT_GOODS/CONSUME/EMPTY_DETAIL_DATA_OUT';


