//根据物品id获取生产单信息
export const FETCH_PRODUCE_ORDER_BY_ID_REQUEST = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PRODUCE_ORDER_BY_ID_REQUEST';
export const FETCH_PRODUCE_ORDER_BY_ID_SUCCESS = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PRODUCE_ORDER_BY_ID_SUCCESS';
export const FETCH_PRODUCE_ORDER_BY_ID_FAILURE = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PRODUCE_ORDER_BY_ID_FAILURE';


export const ASYNC_FETCH_GAIN_MATERIAL_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/ASYNC_FETCH_GAIN_MATERIAL_RECORD';
export const ASYNC_FETCH_QUIT_MATERIAL_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/ASYNC_FETCH_QUIT_MATERIAL_RECORD';
export const ASYNC_FETCH_PRODUCT_ENTER_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/ASYNC_FETCH_PRODUCT_ENTER_RECORD';
export const ASYNC_FETCH_WORK_SHEET_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/ASYNC_FETCH_WORK_SHEET_RECORD';

export const ASYNC_COMPLETE_OPERATE = 'PAGES/PRODUCE_ORDER/SHOW/ASYNC_COMPLETE_OPERATE';
export const ASYNC_REVERT_OPERATE = 'PAGES/PRODUCE_ORDER/SHOW/ASYNC_REVERT_OPERATE';


export const FETCH_PROD_ABSTRACT_FOR_GAIN_MATERIAL_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_GAIN_MATERIAL_RECORD';
export const FETCH_PROD_ABSTRACT_FOR_GAIN_MATERIAL_SUCCESS = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_GAIN_MATERIAL_SUCCESS';
export const FETCH_PROD_ABSTRACT_FOR_GAIN_MATERIAL_FAILURE = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_GAIN_MATERIAL_FAILURE';

export const FETCH_PROD_ABSTRACT_FOR_QUIT_MATERIAL_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_QUIT_MATERIAL_RECORD';
export const FETCH_PROD_ABSTRACT_FOR_QUIT_MATERIAL_SUCCESS = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_QUIT_MATERIAL_SUCCESS';
export const FETCH_PROD_ABSTRACT_FOR_QUIT_MATERIAL_FAILURE = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_QUIT_MATERIAL_FAILURE';

export const FETCH_PROD_ABSTRACT_FOR_PRODUCT_INBOUND_RECORD = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_PRODUCT_INBOUND_RECORD';
export const FETCH_PROD_ABSTRACT_FOR_PRODUCT_INBOUND_SUCCESS = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_PRODUCT_INBOUND_SUCCESS';
export const FETCH_PROD_ABSTRACT_FOR_PRODUCT_INBOUND_FAILURE = 'PAGES/PRODUCE_ORDER/SHOW/FETCH_PROD_ABSTRACT_FOR_PRODUCT_INBOUND_FAILURE';