//订单通知
export const FETCH_ORDER_NOTICE_REQUEST = 'COMPONENTS/LAYOUT/HEADER/FETCH_ORDER_NOTICE_REQUEST';
export const FETCH_ORDER_NOTICE_SUCCESS = 'COMPONENTS/LAYOUT/HEADER/FETCH_ORDER_NOTICE_SUCCESS';
export const FETCH_ORDER_NOTICE_FAILURE = 'COMPONENTS/LAYOUT/HEADER/FETCH_ORDER_NOTICE_FAILURE';

//好友通知
export const FETCH_FRIEND_NOTICE_REQUEST = 'COMPONENTS/LAYOUT/HEADER/FETCH_FRIEND_NOTICE_REQUEST';
export const FETCH_FRIEND_NOTICE_SUCCESS = 'COMPONENTS/LAYOUT/HEADER/FETCH_FRIEND_NOTICE_SUCCESS';
export const FETCH_FRIEND_NOTICE_FAILURE = 'COMPONENTS/LAYOUT/HEADER/FETCH_FRIEND_NOTICE_FAILURE';

//获取消息数量
export const FETCH_NOTICE_COUNT_REQUEST = 'COMPONENTS/LAYOUT/HEADER/FETCH_NOTICE_COUNT_REQUEST';
export const FETCH_NOTICE_COUNT_SUCCESS = 'COMPONENTS/LAYOUT/HEADER/FETCH_NOTICE_COUNT_SUCCESS';
export const FETCH_NOTICE_COUNT_FAILURE = 'COMPONENTS/LAYOUT/HEADER/FETCH_NOTICE_COUNT_FAILURE';

//商城消息置为已读
export const SET_NOTICE_READ_REQUEST = 'COMPONENTS/LAYOUT/HEADER/SET_NOTICE_READ_REQUEST';
export const SET_NOTICE_READ_SUCCESS = 'COMPONENTS/LAYOUT/HEADER/SET_NOTICE_READ_SUCCESS';
export const SET_NOTICE_READ_FAILURE = 'COMPONENTS/LAYOUT/HEADER/SET_NOTICE_READ_FAILURE';