//获取收支列表
export const FETCH_ORDERTYPE_LIST_REQUEST = 'FETCH_ORDERTYPE_LIST_REQUEST';
export const FETCH_ORDERTYPE_LIST_SUCCESS = 'FETCH_ORDERTYPE_LIST_SUCCESS';
export const FETCH_ORDERTYPE_LIST_FAILURE = 'FETCH_ORDERTYPE_LIST_FAILURE';

//新增/修改/删除收支提交
export const ADD_ORDERTYPE_REQUEST = 'ADD_ORDERTYPE_REQUEST';
export const ADD_ORDERTYPE_SUCCESS = 'ADD_ORDERTYPE_SUCCESS';
export const ADD_ORDERTYPE_FAILURE = 'ADD_ORDERTYPE_FAILURE';
