export const TYPE = 'REPORT_INVENTORY_PI';
// 采购到票列表
export const FETCH_REPORT_PI_DETAIL = 'REPORT_PI_DETAIL';
export const FETCH_REPORT_PI_DETAIL_SUCCESS = 'REPORT_PI_DETAIL_SUCCESS';
export const FETCH_REPORT_PI_DETAIL_FAILURE = 'REPORT_PI_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_PI_DETAIL_UPDATE_CONFIG = 'REPORT_PI_DETAIL_UPDATE_CONFIG';

