export const TYPE = 'OUTSOURCE';

// 获取字段配置
export const FETCH_SUBCONTRACT_CONFIG_SUCCESS = "FETCH_SUBCONTRACT_CONFIG_SUCCESS";

export const FETCH_SUBCONTRACT_LIST_REQUEST = 'FETCH_SUBCONTRACT_LIST_REQUEST';
export const FETCH_SUBCONTRACT_LIST_SUCCESS = 'FETCH_SUBCONTRACT_LIST_SUCCESS';
export const FETCH_SUBCONTRACT_LIST_FAILURE = 'FETCH_SUBCONTRACT_LIST_FAILURE';

export const FETCH_OUTSOURCE_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'FETCH_OUTSOURCE_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_OUTSOURCE_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'FETCH_OUTSOURCE_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_OUTSOURCE_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'FETCH_OUTSOURCE_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/SUBCONTRACT/INDEX/FILTER_CONFIG_LIST';
