//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/PURCHASE/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/PURCHASE/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/PURCHASE/ADD/FETCH_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_PURCHASE_REQUEST = 'PAGES/PURCHASE/ADD/ADD_PURCHASE_REQUEST';
export const ADD_PURCHASE_SUCCESS = 'PAGES/PURCHASE/ADD/ADD_PURCHASE_SUCCESS';
export const ADD_PURCHASE_FAILURE = 'PAGES/PURCHASE/ADD/ADD_PURCHASE_FAILURE';

//根据物品id获取物品信息
export const FETCH_PURCHASE_BY_ID_REQUEST = 'PAGES/PURCHASE/ADD/FETCH_PURCHASE_BY_ID_REQUEST';
export const FETCH_PURCHASE_BY_ID_SUCCESS = 'PAGES/PURCHASE/ADD/FETCH_PURCHASE_BY_ID_SUCCESS';
export const FETCH_PURCHASE_BY_ID_FAILURE = 'PAGES/PURCHASE/ADD/FETCH_PURCHASE_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/PURCHASE/ADD/EMPTY_DETAIL_DATA';

//绑定、取消绑定
export const UPDATE_BIND_PRODUCT_INFO = 'PAGES/PURCHASE/DETAIL/UPDATE_BIND_PRODUCT_INFO';
export const REQUEST_BIND_PRODUCT = 'PAGES/PURCHASE/DETAIL/REQUEST_BIND_PRODUCT_INFO';
export const REQUEST_BIND_PRODUCT_SUCCESS = 'PAGES/PURCHASE/DETAIL/REQUEST_BIND_PRODUCT_SUCCESS';
export const REQUEST_BIND_PRODUCT_FAILED = 'PAGES/PURCHASE/DETAIL/REQUEST_BIND_PRODUCT_FAILED';

//获取操作日志
export const ASYNC_FETCH_OPERATION_LOG_REQUEST = 'PAGES/PURCHASE/ADD/ASYNC_FETCH_OPERATION_LOG_REQUEST';
export const ASYNC_FETCH_OPERATION_LOG_SUCCESS = 'PAGES/PURCHASE/ADD/ASYNC_FETCH_OPERATION_LOG_SUCCESS';
export const ASYNC_FETCH_OPERATION_LOG_FAILURE = 'PAGES/PURCHASE/ADD/ASYNC_FETCH_OPERATION_LOG_FAILURE';




