export const AUTH_ADD = 'AUTH_ADD';
export const AUTH_DELETE = 'AUTH_DELETE';
export const AUTH_MODIFY = 'AUTH_MODIFY';
export const AUTH_READ = 'AUTH_READ';
export const AUTH_APPROVE = 'AUTH_APPROVE';
export const AUTH_APPENDIX='AUTH_APPENDIX';

//获取子账号权限
export const FETCH_SUB_ACCOUNT_AUTH_REQUEST = 'FETCH_SUB_ACCOUNT_AUTH_REQUEST';
export const FETCH_SUB_ACCOUNT_AUTH_SUCCESS = 'FETCH_SUB_ACCOUNT_AUTH_SUCCESS';
export const FETCH_SUB_ACCOUNT_AUTH_FAILURE = 'FETCH_SUB_ACCOUNT_AUTH_FAILURE';


//提交子账号权限
export const SUBMIT_SUB_ACCOUNT_AUTH_REQUEST = 'SUBMIT_SUB_ACCOUNT_AUTH_REQUEST';
export const SUBMIT_SUB_ACCOUNT_AUTH_SUCCESS = 'SUBMIT_SUB_ACCOUNT_AUTH_SUCCESS';
export const SUBMIT_SUB_ACCOUNT_AUTH_FAILURE = 'SUBMIT_SUB_ACCOUNT_AUTH_FAILURE';

export const EMPTY_SUB_ACCOUNT_AUTH = 'EMPTY_SUB_ACCOUNT_AUTH';