// 配件组合列表
export const FITTING_LIST = 'FITTING_LIST';
export const FITTING_LIST_SUCCESS = 'FITTING_LIST_SUCCESS';
export const FITTING_LIST_FAILURE = 'FITTING_LIST_FAILURE';

export const DEFAULT_FITTING_SUCCESS = 'DEFAULT_FITTING_SUCCESS';
export const SET_FITTING_INFO = 'SET_FITTING_INFO';
export const SET_FITTING_LIST = 'SET_FITTING_LIST';

export const GET_LOCAL_FITTING_INFO = 'GET_LOCAL_FITTING_INFO';

export const FITTING_CONFIRM_FETCHING_TRUE = 'FITTING_CONFIRM_FETCHING_TRUE';
export const FITTING_CONFIRM_FETCHING_FALSE = 'FITTING_CONFIRM_FETCHING_FALSE';

// 通过编号查询具体bom组合的信息
export const FETCH_PROD_COMBINATIONS_LIST = 'FETCH_PROD_COMBINATIONS_LIST';


//判断是否属于成品 并返回符合的物品编号和数量
export const JUDGE_IS_BELONG_BOM = 'JUDGE_IS_BELONG_BOM';
