
//获取页面初始数据
export const FETCH_INBOUND_PRE_DATA_REQUEST = 'FETCH_INBOUND_PRE_DATA_REQUEST';
export const FETCH_INBOUND_PRE_DATA_SUCCESS = 'FETCH_INBOUND_PRE_DATA_SUCCESS';
export const FETCH_INBOUND_PRE_DATA_FAILURE = 'FETCH_INBOUND_PRE_DATA_FAILURE';

//新增物品提交
export const ADD_SALE_REQUEST = 'SALE/ADD/ADD_SALE_REQUEST';
export const ADD_SALE_SUCCESS = 'SALE/ADD/ADD_SALE_SUCCESS';
export const ADD_SALE_FAILURE = 'SALE/ADD/ADD_SALE_FAILURE';

//根据物品id获取物品信息
export const FETCH_SALE_BY_ID_REQUEST = 'SALE/ADD/FETCH_SALE_BY_ID_REQUEST';
export const FETCH_SALE_BY_ID_SUCCESS = 'SALE/ADD/FETCH_SALE_BY_ID_SUCCESS';
export const FETCH_SALE_BY_ID_FAILURE = 'SALE/ADD/FETCH_SALE_BY_ID_FAILURE';

export const EMPTY_DETAIL_DATA = 'SALE/ADD/EMPTY_DETAIL_DATA';




