
export const FETCH_WORK_ORDER_CHART_REQUEST = 'FETCH_WORK_ORDER_CHART_REQUEST';
export const FETCH_WORK_ORDER_CHART_SUCCESS = 'FETCH_WORK_ORDER_CHART_SUCCESS';
export const FETCH_WORK_ORDER_CHART_FAILURE = 'FETCH_WORK_ORDER_CHART_FAILURE';


