export const TYPE = 'REPORT_FETCH_COLLECTION_DELIVERY';
// 获取领用出库汇总表（按部门）
export const FETCH_COLLECTION_DELIVERY = 'PAGES/REPORT/FETCH_COLLECTION_DELIVERY';

// 更新配置字段
// export const FETCH_SALE_REFUND_SUMMARY_BY_PROD = 'REPORT_SALE_REFUND_SUMMARY_BY_PROD_DETAIL_UPDATE_CONFIG';

