//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/INQUIRY/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/INQUIRY/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/INQUIRY/ADD/FETCH_PRE_DATA_FAILURE';

//根据物品名称获取匹配百卓目录
export const FETCH_CATE_BY_NAME_REQUEST = 'PAGES/INQUIRY/ADD/FETCH_CATE_BY_NAME_REQUEST';
export const FETCH_CATE_BY_NAME_SUCCESS = 'PAGES/INQUIRY/ADD/FETCH_CATE_BY_NAME_SUCCESS';
export const FETCH_CATE_BY_NAME_FAILURE = 'PAGES/INQUIRY/ADD/FETCH_CATE_BY_NAME_FAILURE';

//新增物品提交
export const ADD_INQUIRY_REQUEST = 'PAGES/INQUIRY/ADD/ADD_INQUIRY_REQUEST';
export const ADD_INQUIRY_SUCCESS = 'PAGES/INQUIRY/ADD/ADD_INQUIRY_SUCCESS';
export const ADD_INQUIRY_FAILURE = 'PAGES/INQUIRY/ADD/ADD_INQUIRY_FAILURE';

//根据物品id获取物品信息
export const FETCH_INQUIRY_BY_ID_REQUEST = 'PAGES/INQUIRY/ADD/FETCH_INQUIRY_BY_ID_REQUEST';
export const FETCH_INQUIRY_BY_ID_SUCCESS = 'PAGES/INQUIRY/ADD/FETCH_INQUIRY_BY_ID_SUCCESS';
export const FETCH_INQUIRY_BY_ID_FAILURE = 'PAGES/INQUIRY/ADD/FETCH_INQUIRY_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/INQUIRY/ADD/EMPTY_DETAIL_DATA';


