// 仓库列表
export const WAREHOUSE_LIST = 'WAREHOUSE_LIST';
export const WAREHOUSE_LIST_SUCCESS = 'WAREHOUSE_LIST_SUCCESS';
export const WAREHOUSE_LIST_FAILURE = 'WAREHOUSE_LIST_FAILURE';

export const DEFAULT_WAREHOUSE_SUCCESS = 'DEFAULT_WAREHOUSE_SUCCESS';
export const DEFAULT_WAREHOUSE_FAILURE = 'DEFAULT_WAREHOUSE_FAILURE';

export const GET_LOCAL_WAREHOUSE_INFO = 'GET_LOCAL_WAREHOUSE_INFO';

export const WAREHOUSE_CONFIRM_FETCHING_TRUE = 'WAREHOUSE_CONFIRM_FETCHING_TRUE';
export const WAREHOUSE_CONFIRM_FETCHING_FALSE = 'WAREHOUSE_CONFIRM_FETCHING_FALSE';

