export const TYPE = 'REPORT_TRADE_SALE_PROFIT';
// 获取物品列表
export const FETCH_TRADE_SALE_PROFIT_DETAIL = 'FETCH_TRADE_SALE_PROFIT_DETAIL';
export const FETCH_TRADE_SALE_PROFIT_DETAIL_SUCCESS = 'FETCH_TRADE_SALE_PROFIT_DETAIL_SUCCESS';
export const FETCH_TRADE_SALE_PROFIT_DETAIL_FAILURE = 'FETCH_TRADE_SALE_PROFIT_DETAIL_FAILURE';

// 更新配置字段
export const REPORT_TRADE_SALE_PROFIT_DETAIL_UPDATE_CONFIG = 'REPORT_TRADE_SALE_PROFIT_DETAIL_UPDATE_CONFIG';

