//获取报工账号列表
export const FETCH_ACCOUNT_REPORT_LIST_REQUEST = 'FETCH_ACCOUNT_REPORT_LIST_REQUEST';
export const FETCH_ACCOUNT_REPORT_LIST_SUCCESS = 'FETCH_ACCOUNT_REPORT_LIST_SUCCESS';
export const FETCH_ACCOUNT_REPORT_LIST_FAILURE = 'FETCH_ACCOUNT_REPORT_LIST_FAILURE';

//新增/修改/删除报工账号
export const ADD_ACCOUNT_REPORT_REQUEST = 'ADD_ACCOUNT_REPORT_REQUEST';
export const ADD_ACCOUNT_REPORT_SUCCESS = 'ADD_ACCOUNT_REPORT_SUCCESS';
export const ADD_ACCOUNT_REPORT_FAILURE = 'ADD_ACCOUNT_REPORT_FAILURE';
