//销售订单动态
export const FETCH_SALE_ORDER_REQUEST = 'PAGES/HOME/FETCH_SALE_ORDER_REQUEST';
export const FETCH_SALE_ORDER_SUCCESS = 'PAGES/HOME/FETCH_SALE_ORDER_SUCCESS';
export const FETCH_SALE_ORDER_FAILURE = 'PAGES/HOME/FETCH_SALE_ORDER_FAILURE';

//设置销售订单只读
export const SET_SALE_ORDER_READ_REQUEST= 'PAGES/HOME/SET_SALE_ORDER_READ_REQUEST';
export const SET_SALE_ORDER_READ_SUCCESS= 'PAGES/HOME/SET_SALE_ORDER_READ_SUCCESS';
export const SET_SALE_ORDER_READ_FAILURE= 'PAGES/HOME/SET_SALE_ORDER_READ_FAILURE';

//采购订单动态
export const FETCH_PURCHASE_ORDER_REQUEST = 'PAGES/HOME/FETCH_PURCHASE_ORDER_REQUEST';
export const FETCH_PURCHASE_ORDER_SUCCESS = 'PAGES/HOME/FETCH_PURCHASE_ORDER_SUCCESS';
export const FETCH_PURCHASE_ORDER_FAILURE = 'PAGES/HOME/FETCH_PURCHASE_ORDER_FAILURE';

//设置销售订单只读
export const SET_PURCHASE_ORDER_READ_REQUEST= 'PAGES/HOME/SET_PURCHASE_ORDER_READ_REQUEST';
export const SET_PURCHASE_ORDER_READ_SUCCESS= 'PAGES/HOME/SET_PURCHASE_ORDER_READ_SUCCESS';
export const SET_PURCHASE_ORDER_READ_FAILURE= 'PAGES/HOME/SET_PURCHASE_ORDER_READ_FAILURE';

//通知公告
export const FETCH_NOTICE_REQUEST = 'PAGES/HOME/FETCH_NOTICE_REQUEST';
export const FETCH_NOTICE_SUCCESS = 'PAGES/HOME/FETCH_NOTICE_SUCCESS';
export const FETCH_NOTICE_FAILURE = 'PAGES/HOME/FETCH_NOTICE_FAILURE';

//邀请加好友
export const FETCH_INVITE_FRIEND_REQUEST = 'PAGES/HOME/FETCH_INVITE_FRIEND_REQUEST';
export const FETCH_INVITE_FRIEND_SUCCESS = 'PAGES/HOME/FETCH_INVITE_FRIEND_SUCCESS';
export const FETCH_INVITE_FRIEND_FAILURE = 'PAGES/HOME/FETCH_INVITE_FRIEND_FAILURE';

//采购支出统计
export const FETCH_ORDER_REQUEST = 'PAGES/HOME/FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'PAGES/HOME/FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'PAGES/HOME/FETCH_ORDER_FAILURE';

//销售收入统计
export const FETCH_SALE_REQUEST = 'PAGES/HOME/FETCH_SALE_REQUEST';
export const FETCH_SALE_SUCCESS = 'PAGES/HOME/FETCH_SALE_SUCCESS';
export const FETCH_SALE_FAILURE = 'PAGES/HOME/FETCH_SALE_FAILURE';

//物品数据
export const FETCH_STORE_GOODS_REQUEST = 'PAGES/HOME/FETCH_STORE_GOODS_REQUEST';
export const FETCH_STORE_GOODS_SUCCESS = 'PAGES/HOME/FETCH_STORE_GOODS_SUCCESS';
export const FETCH_STORE_GOODS_FAILURE = 'PAGES/HOME/FETCH_STORE_GOODS_FAILURE';

//分销物品数据
export const FETCH_STORE_DISTRIBUTION_GOODS_REQUEST = 'PAGES/HOME/FETCH_STORE_DISTRIBUTION_GOODS_REQUEST';
export const FETCH_STORE_DISTRIBUTION_GOODS_SUCCESS = 'PAGES/HOME/FETCH_STORE_DISTRIBUTION_GOODS_SUCCESS';
export const FETCH_STORE_DISTRIBUTION_GOODS_FAILURE = 'PAGES/HOME/FETCH_STORE_DISTRIBUTION_GOODS_FAILURE';