//获取收支列表
export const FETCH_LEVEL_APPROVED_LIST_REQUEST = 'FETCH_LEVEL_APPROVED_LIST_REQUEST';
export const FETCH_LEVEL_APPROVED_LIST_SUCCESS = 'FETCH_LEVEL_APPROVED_LIST_SUCCESS';
export const FETCH_LEVEL_APPROVED_LIST_FAILURE = 'FETCH_LEVEL_APPROVED_LIST_FAILURE';

export const FETCH_LEVEL_APPROVED_LIST_EMPTY = 'FETCH_LEVEL_APPROVED_LIST_EMPTY';

//新增/修改/删除收支提交
export const ADD_LEVEL_APPROVED_REQUEST = 'ADD_LEVEL_APPROVED_REQUEST';
export const ADD_LEVEL_APPROVED_SUCCESS = 'ADD_LEVEL_APPROVED_SUCCESS';
export const ADD_LEVEL_APPROVED_FAILURE = 'ADD_LEVEL_APPROVED_FAILURE';
