
//初始化列表数据
export const FETCH_ONLINE_ORDER_COMPANY_LIST_DATA_SUCCESS = 'FETCH_ONLINE_ORDER_COMPANY_LIST_DATA_SUCCESS';
//获取数据失败
export const FETCH_ONLINE_ORDER_COMPANY_LIST_DATA_FAILURE = 'FETCH_ONLINE_ORDER_COMPANY_LIST_DATA_FAILURE';
//获取购物车数量
export const FETCH_ONLINE_ORDER_COMPANY_LIST_GET_CART_AMOUNT = 'FETCH_ONLINE_ORDER_COMPANY_LIST_GET_CART_AMOUNT';

