export const TYPE = 'PRODUCE_ORDER';

// 获取字段配置
export const FETCH_PRODUCE_ORDER_CONFIG_SUCCESS = "PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_ORDER_CONFIG_SUCCESS";

export const FETCH_PRODUCE_ORDER_LIST_REQUEST = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_ORDER_LIST_REQUEST';
export const FETCH_PRODUCE_ORDER_LIST_SUCCESS = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_ORDER_LIST_SUCCESS';
export const FETCH_PRODUCE_ORDER_LIST_FAILURE = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_ORDER_LIST_FAILURE';

// 列表返回带回初始化数据
export const FILTER_CONFIG_LIST = 'PAGES/PRODUCE_ORDER/INDEX/FILTER_CONFIG_LIST';


// 根据单号获取物品概要的总类
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_REQUEST';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_SUCCESS';
export const FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PROD_ABSTRACT_BY_BILL_NO_FAILURE';

// 批量选择bom，返回配件
export const FETCH_PRODUCE_FITTING_LIST = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_FITTING_LIST';

export const FETCH_PRODUCE_RECORD_REQUEST = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_RECORD_REQUEST';
export const FETCH_PRODUCE_RECORD_SUCCESS = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_RECORD_SUCCESS';
export const FETCH_PRODUCE_RECORD_FAILURE = 'PAGES/PRODUCE_ORDER/INDEX/FETCH_PRODUCE_RECORD_FAILURE';


