//开通商城
export const FETCH_OPEN_MALL_REQUEST = 'COMPONENTS/BUSINESS/VIP_OPE/FETCH_OPEN_MALL_REQUEST';
export const FETCH_OPEN_MALL_SUCCESS = 'COMPONENTS/BUSINESS/VIP_OPE/FETCH_OPEN_MALL_SUCCESS';
export const FETCH_OPEN_MALL_FAILURE = 'COMPONENTS/BUSINESS/VIP_OPE/FETCH_OPEN_MALL_FAILURE';
