//获取物品单位列表
export const FETCH_DELIVERY_ADDR_LIST_REQUEST = 'FETCH_DELIVERY_ADDR_LIST_REQUEST';
export const FETCH_DELIVERY_ADDR_LIST_SUCCESS = 'FETCH_DELIVERY_ADDR_LIST_SUCCESS';
export const FETCH_DELIVERY_ADDR_LIST_FAILURE = 'FETCH_DELIVERY_ADDR_LIST_FAILURE';

//新增/修改/删除物品单位提交
export const ADD_DELIVERY_ADDR_REQUEST = 'ADD_DELIVERY_ADDR_REQUEST';
export const ADD_DELIVERY_ADDR_SUCCESS = 'ADD_DELIVERY_ADDR_SUCCESS';
export const ADD_DELIVERY_ADDR_FAILURE = 'ADD_DELIVERY_ADDR_FAILURE';
