//初始化报价单新增页面数据
export const FETCH_INIT_QUOTATION_DETAIL = 'FETCH_INIT_QUOTATION_DETAIL';

//提交报价单
export const FETCH_ADD_QUOTATION = 'FETCH_ADD_QUOTATION';

//上传图片
export const FETCH_APP_UPLOAD_PIC = 'FETCH_APP_UPLOAD_PIC';
