export const TYPE = 'REPORT_WARE_SUMMARY';
// 获取物品列表
export const FETCH_REPORT_WARE_SUMMARY = 'REPORT_WARE_SUMMARY';
export const FETCH_REPORT_WARE_SUMMARY_SUCCESS = 'REPORT_WARE_SUMMARY_SUCCESS';
export const FETCH_REPORT_WARE_SUMMARY_FAILURE = 'REPORT_WARE_SUMMARY_FAILURE';

// 更新配置字段
export const REPORT_WARE_SUMMARY_UPDATE_CONFIG = 'REPORT_WARE_SUMMARY_UPDATE_CONFIG';

