//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/PRODUCE_ORDER/ADD/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/PRODUCE_ORDER/ADD/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/PRODUCE_ORDER/ADD/FETCH_PRE_DATA_FAILURE';

//新增生产单提交
export const ADD_PRODUCE_ORDER_REQUEST = 'PAGES/PRODUCE_ORDER/ADD/ADD_PRODUCE_ORDER_REQUEST';
export const ADD_PRODUCE_ORDER_SUCCESS = 'PAGES/PRODUCE_ORDER/ADD/ADD_PRODUCE_ORDER_SUCCESS';
export const ADD_PRODUCE_ORDER_FAILURE = 'PAGES/PRODUCE_ORDER/ADD/ADD_PRODUCE_ORDER_FAILURE';

//根据物品id获取生产单信息
export const FETCH_PRODUCE_ORDER_BY_ID_REQUEST = 'PAGES/PRODUCE_ORDER/ADD/FETCH_PRODUCE_ORDER_BY_ID_REQUEST';
export const FETCH_PRODUCE_ORDER_BY_ID_SUCCESS = 'PAGES/PRODUCE_ORDER/ADD/FETCH_PRODUCE_ORDER_BY_ID_SUCCESS';
export const FETCH_PRODUCE_ORDER_BY_ID_FAILURE = 'PAGES/PRODUCE_ORDER/ADD/FETCH_PRODUCE_ORDER_BY_ID_FAILURE';

//清空
export const EMPTY_DETAIL_DATA = 'PAGES/PRODUCE_ORDER/ADD/EMPTY_DETAIL_DATA';

export const FETCH_SALE_ORDER_POP_LIST_REQUEST = 'PAGES/PRODUCE_ORDER/ADD/FETCH_SALE_ORDER_POP_LIST_REQUEST';
export const FETCH_SALE_ORDER_POP_LIST_SUCCESS = 'PAGES/PRODUCE_ORDER/ADD/FETCH_SALE_ORDER_POP_LIST_SUCCESS';
export const FETCH_SALE_ORDER_POP_LIST_FAILURE = 'PAGES/PRODUCE_ORDER/ADD/FETCH_SALE_ORDER_POP_LIST_FAILURE';
export const SET_SALE_ORDER_POP = 'PAGES/PRODUCE_ORDER/ADD/SET_SALE_ORDER_POP';






